// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AdminAccountDeletePayload struct {
	Success bool `json:"success"`
}

type AdminAuthPayload struct {
	Success bool       `json:"success"`
	User    *AdminUser `json:"user,omitempty"`
}

type AdminChangeAvatarInput struct {
	AvatarURL *string `json:"avatarUrl,omitempty"`
}

type AdminChangeNameInput struct {
	Name string `json:"name"`
}

type AdminChangePasswordInput struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
	ConfirmPassword string `json:"confirmPassword"`
}

type AdminChangeUsernameInput struct {
	NewUsername string `json:"newUsername"`
}

type AdminDashboard struct {
	TotalPosts       int                          `json:"totalPosts"`
	TotalSubscribers int                          `json:"totalSubscribers"`
	TopViewedPosts   []*AdminDashboardPost        `json:"topViewedPosts"`
	TopLikedPosts    []*AdminDashboardPost        `json:"topLikedPosts"`
	ContentHealth    *AdminDashboardContentHealth `json:"contentHealth"`
}

type AdminDashboardCategory struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Count int    `json:"count"`
}

type AdminDashboardContentHealth struct {
	LocalePairCoverage  int                          `json:"localePairCoverage"`
	MissingTranslations int                          `json:"missingTranslations"`
	MissingThumbnails   int                          `json:"missingThumbnails"`
	LatestUpdatedPosts  []*AdminDashboardUpdatedPost `json:"latestUpdatedPosts"`
	DominantCategory    *AdminDashboardCategory      `json:"dominantCategory,omitempty"`
}

type AdminDashboardPost struct {
	PostID        string `json:"postId"`
	Title         string `json:"title"`
	Locale        string `json:"locale"`
	PublishedDate string `json:"publishedDate"`
	Hits          int    `json:"hits"`
	Likes         int    `json:"likes"`
}

type AdminDashboardUpdatedPost struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Date     string `json:"date"`
	Category string `json:"category"`
}

type AdminDeleteAccountInput struct {
	CurrentPassword string `json:"currentPassword"`
}

type AdminLoginInput struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	RememberMe *bool  `json:"rememberMe,omitempty"`
}

type AdminLogoutPayload struct {
	Success bool `json:"success"`
}

type AdminMe struct {
	Authenticated bool       `json:"authenticated"`
	User          *AdminUser `json:"user,omitempty"`
}

type AdminMutation struct {
}

type AdminPasswordChangePayload struct {
	Success bool `json:"success"`
}

type AdminQuery struct {
}

type AdminSession struct {
	ID             string `json:"id"`
	Device         string `json:"device"`
	IPAddress      string `json:"ipAddress"`
	CountryCode    string `json:"countryCode"`
	LastActivityAt string `json:"lastActivityAt"`
	CreatedAt      string `json:"createdAt"`
	ExpiresAt      string `json:"expiresAt"`
	Persistent     bool   `json:"persistent"`
	Current        bool   `json:"current"`
}

type AdminSessionRevokePayload struct {
	Success bool `json:"success"`
}

type AdminUser struct {
	ID        string   `json:"id"`
	Name      *string  `json:"name,omitempty"`
	Username  *string  `json:"username,omitempty"`
	AvatarURL *string  `json:"avatarUrl,omitempty"`
	Email     string   `json:"email"`
	Roles     []string `json:"roles"`
}
