// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AdminAccountDeletePayload struct {
	Success bool `json:"success"`
}

type AdminAuthPayload struct {
	Success bool       `json:"success"`
	User    *AdminUser `json:"user,omitempty"`
}

type AdminChangeAvatarInput struct {
	AvatarURL *string `json:"avatarUrl,omitempty"`
}

type AdminChangeNameInput struct {
	Name string `json:"name"`
}

type AdminChangePasswordInput struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
	ConfirmPassword string `json:"confirmPassword"`
}

type AdminChangeUsernameInput struct {
	NewUsername string `json:"newUsername"`
}

type AdminComment struct {
	ID          string             `json:"id"`
	PostID      string             `json:"postId"`
	PostTitle   string             `json:"postTitle"`
	Locale      string             `json:"locale"`
	ParentID    *string            `json:"parentId,omitempty"`
	AuthorName  string             `json:"authorName"`
	AuthorEmail string             `json:"authorEmail"`
	Content     string             `json:"content"`
	Status      AdminCommentStatus `json:"status"`
	CreatedAt   time.Time          `json:"createdAt"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

type AdminCommentFilterInput struct {
	Locale *string             `json:"locale,omitempty"`
	Status *AdminCommentStatus `json:"status,omitempty"`
	PostID *string             `json:"postId,omitempty"`
	Query  *string             `json:"query,omitempty"`
	Page   *int                `json:"page,omitempty"`
	Size   *int                `json:"size,omitempty"`
}

type AdminCommentListPayload struct {
	Items []*AdminComment `json:"items"`
	Total int             `json:"total"`
	Page  int             `json:"page"`
	Size  int             `json:"size"`
}

type AdminContentCategory struct {
	Locale    string     `json:"locale"`
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Color     string     `json:"color"`
	Icon      *string    `json:"icon,omitempty"`
	Link      *string    `json:"link,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type AdminContentCategoryGroup struct {
	ID        string                `json:"id"`
	Preferred *AdminContentCategory `json:"preferred"`
	En        *AdminContentCategory `json:"en,omitempty"`
	Tr        *AdminContentCategory `json:"tr,omitempty"`
}

type AdminContentCategoryInput struct {
	Locale string  `json:"locale"`
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	Color  string  `json:"color"`
	Icon   *string `json:"icon,omitempty"`
	Link   *string `json:"link,omitempty"`
}

type AdminContentCategoryListPayload struct {
	Items []*AdminContentCategoryGroup `json:"items"`
	Total int                          `json:"total"`
	Page  int                          `json:"page"`
	Size  int                          `json:"size"`
}

type AdminContentEntityKeyInput struct {
	Locale string `json:"locale"`
	ID     string `json:"id"`
}

type AdminContentPost struct {
	Locale           string     `json:"locale"`
	ID               string     `json:"id"`
	Title            string     `json:"title"`
	Summary          *string    `json:"summary,omitempty"`
	Content          *string    `json:"content,omitempty"`
	ContentMode      *string    `json:"contentMode,omitempty"`
	Thumbnail        *string    `json:"thumbnail,omitempty"`
	Source           string     `json:"source"`
	PublishedDate    string     `json:"publishedDate"`
	UpdatedDate      *string    `json:"updatedDate,omitempty"`
	CategoryID       *string    `json:"categoryId,omitempty"`
	CategoryName     *string    `json:"categoryName,omitempty"`
	TopicIds         []string   `json:"topicIds"`
	TopicNames       []string   `json:"topicNames"`
	ContentUpdatedAt *time.Time `json:"contentUpdatedAt,omitempty"`
	UpdatedAt        *time.Time `json:"updatedAt,omitempty"`
}

type AdminContentPostFilterInput struct {
	Locale          *string `json:"locale,omitempty"`
	PreferredLocale *string `json:"preferredLocale,omitempty"`
	Source          *string `json:"source,omitempty"`
	Query           *string `json:"query,omitempty"`
	CategoryID      *string `json:"categoryId,omitempty"`
	TopicID         *string `json:"topicId,omitempty"`
	Page            *int    `json:"page,omitempty"`
	Size            *int    `json:"size,omitempty"`
}

type AdminContentPostGroup struct {
	ID        string            `json:"id"`
	Source    string            `json:"source"`
	Preferred *AdminContentPost `json:"preferred"`
	En        *AdminContentPost `json:"en,omitempty"`
	Tr        *AdminContentPost `json:"tr,omitempty"`
}

type AdminContentPostListPayload struct {
	Items []*AdminContentPostGroup `json:"items"`
	Total int                      `json:"total"`
	Page  int                      `json:"page"`
	Size  int                      `json:"size"`
}

type AdminContentTaxonomyFilterInput struct {
	Locale          *string `json:"locale,omitempty"`
	PreferredLocale *string `json:"preferredLocale,omitempty"`
	Query           *string `json:"query,omitempty"`
	Page            *int    `json:"page,omitempty"`
	Size            *int    `json:"size,omitempty"`
}

type AdminContentTopic struct {
	Locale    string     `json:"locale"`
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Color     string     `json:"color"`
	Link      *string    `json:"link,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type AdminContentTopicGroup struct {
	ID        string             `json:"id"`
	Preferred *AdminContentTopic `json:"preferred"`
	En        *AdminContentTopic `json:"en,omitempty"`
	Tr        *AdminContentTopic `json:"tr,omitempty"`
}

type AdminContentTopicInput struct {
	Locale string  `json:"locale"`
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	Color  string  `json:"color"`
	Link   *string `json:"link,omitempty"`
}

type AdminContentTopicListPayload struct {
	Items []*AdminContentTopicGroup `json:"items"`
	Total int                       `json:"total"`
	Page  int                       `json:"page"`
	Size  int                       `json:"size"`
}

type AdminCreateErrorMessageInput struct {
	Key     *AdminErrorMessageKeyInput `json:"key"`
	Message string                     `json:"message"`
}

type AdminDashboard struct {
	TotalPosts       int                          `json:"totalPosts"`
	TotalSubscribers int                          `json:"totalSubscribers"`
	TopViewedPosts   []*AdminDashboardPost        `json:"topViewedPosts"`
	TopLikedPosts    []*AdminDashboardPost        `json:"topLikedPosts"`
	ContentHealth    *AdminDashboardContentHealth `json:"contentHealth"`
}

type AdminDashboardCategory struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Count int    `json:"count"`
}

type AdminDashboardContentHealth struct {
	LocalePairCoverage  int                          `json:"localePairCoverage"`
	MissingTranslations int                          `json:"missingTranslations"`
	MissingThumbnails   int                          `json:"missingThumbnails"`
	LatestUpdatedPosts  []*AdminDashboardUpdatedPost `json:"latestUpdatedPosts"`
	DominantCategory    *AdminDashboardCategory      `json:"dominantCategory,omitempty"`
}

type AdminDashboardPost struct {
	PostID        string `json:"postId"`
	Title         string `json:"title"`
	Locale        string `json:"locale"`
	PublishedDate string `json:"publishedDate"`
	Hits          int    `json:"hits"`
	Likes         int    `json:"likes"`
}

type AdminDashboardUpdatedPost struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Date     string `json:"date"`
	Category string `json:"category"`
}

type AdminDeleteAccountInput struct {
	CurrentPassword string `json:"currentPassword"`
}

type AdminDeleteCommentInput struct {
	CommentID string `json:"commentId"`
}

type AdminDeleteNewsletterSubscriberInput struct {
	Email string `json:"email"`
}

type AdminDeletePayload struct {
	Success bool `json:"success"`
}

type AdminEmailChangeRequestPayload struct {
	Success      bool      `json:"success"`
	PendingEmail string    `json:"pendingEmail"`
	ExpiresAt    time.Time `json:"expiresAt"`
}

type AdminErrorMessage struct {
	Scope     string     `json:"scope"`
	Locale    string     `json:"locale"`
	Code      string     `json:"code"`
	Message   string     `json:"message"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type AdminErrorMessageAuditLog struct {
	ID          string    `json:"id"`
	ActorID     string    `json:"actorId"`
	ActorEmail  string    `json:"actorEmail"`
	Action      string    `json:"action"`
	Scope       string    `json:"scope"`
	Locale      string    `json:"locale"`
	Code        string    `json:"code"`
	BeforeValue string    `json:"beforeValue"`
	AfterValue  string    `json:"afterValue"`
	Status      string    `json:"status"`
	FailureCode *string   `json:"failureCode,omitempty"`
	RequestID   *string   `json:"requestId,omitempty"`
	RemoteIP    *string   `json:"remoteIp,omitempty"`
	CountryCode *string   `json:"countryCode,omitempty"`
	UserAgent   *string   `json:"userAgent,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
}

type AdminErrorMessageFilterInput struct {
	Locale *string `json:"locale,omitempty"`
	Code   *string `json:"code,omitempty"`
	Query  *string `json:"query,omitempty"`
	Page   *int    `json:"page,omitempty"`
	Size   *int    `json:"size,omitempty"`
}

type AdminErrorMessageKeyInput struct {
	Scope  *string `json:"scope,omitempty"`
	Locale string  `json:"locale"`
	Code   string  `json:"code"`
}

type AdminErrorMessageListPayload struct {
	Items []*AdminErrorMessage `json:"items"`
	Total int                  `json:"total"`
	Page  int                  `json:"page"`
	Size  int                  `json:"size"`
}

type AdminGithubAuthStatus struct {
	Enabled        bool `json:"enabled"`
	LoginAvailable bool `json:"loginAvailable"`
}

type AdminGithubConnectPayload struct {
	URL string `json:"url"`
}

type AdminGithubDisconnectPayload struct {
	Success bool       `json:"success"`
	User    *AdminUser `json:"user,omitempty"`
}

type AdminGoogleAuthStatus struct {
	Enabled        bool `json:"enabled"`
	LoginAvailable bool `json:"loginAvailable"`
}

type AdminGoogleConnectPayload struct {
	URL string `json:"url"`
}

type AdminGoogleDisconnectPayload struct {
	Success bool       `json:"success"`
	User    *AdminUser `json:"user,omitempty"`
}

type AdminLoginInput struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	RememberMe *bool  `json:"rememberMe,omitempty"`
}

type AdminLogoutPayload struct {
	Success bool `json:"success"`
}

type AdminMe struct {
	Authenticated bool       `json:"authenticated"`
	User          *AdminUser `json:"user,omitempty"`
}

type AdminMutation struct {
}

type AdminNewsletterCampaign struct {
	Locale      string     `json:"locale"`
	ItemKey     string     `json:"itemKey"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary,omitempty"`
	Link        *string    `json:"link,omitempty"`
	PubDate     *string    `json:"pubDate,omitempty"`
	RssURL      *string    `json:"rssUrl,omitempty"`
	Status      string     `json:"status"`
	SentCount   int        `json:"sentCount"`
	FailedCount int        `json:"failedCount"`
	LastRunAt   *time.Time `json:"lastRunAt,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
}

type AdminNewsletterCampaignFilterInput struct {
	Locale *string `json:"locale,omitempty"`
	Status *string `json:"status,omitempty"`
	Query  *string `json:"query,omitempty"`
	Page   *int    `json:"page,omitempty"`
	Size   *int    `json:"size,omitempty"`
}

type AdminNewsletterCampaignListPayload struct {
	Items []*AdminNewsletterCampaign `json:"items"`
	Total int                        `json:"total"`
	Page  int                        `json:"page"`
	Size  int                        `json:"size"`
}

type AdminNewsletterDeliveryFailure struct {
	Locale        string     `json:"locale"`
	ItemKey       string     `json:"itemKey"`
	Email         string     `json:"email"`
	Status        string     `json:"status"`
	LastError     *string    `json:"lastError,omitempty"`
	LastAttemptAt *time.Time `json:"lastAttemptAt,omitempty"`
	UpdatedAt     *time.Time `json:"updatedAt,omitempty"`
	CreatedAt     *time.Time `json:"createdAt,omitempty"`
}

type AdminNewsletterDeliveryFailureFilterInput struct {
	Locale  string `json:"locale"`
	ItemKey string `json:"itemKey"`
	Page    *int   `json:"page,omitempty"`
	Size    *int   `json:"size,omitempty"`
}

type AdminNewsletterDeliveryFailureListPayload struct {
	Items []*AdminNewsletterDeliveryFailure `json:"items"`
	Total int                               `json:"total"`
	Page  int                               `json:"page"`
	Size  int                               `json:"size"`
}

type AdminNewsletterDispatchLocaleResult struct {
	Locale      string  `json:"locale"`
	RssURL      *string `json:"rssUrl,omitempty"`
	ItemKey     *string `json:"itemKey,omitempty"`
	PostTitle   *string `json:"postTitle,omitempty"`
	SentCount   int     `json:"sentCount"`
	FailedCount int     `json:"failedCount"`
	Skipped     bool    `json:"skipped"`
	Reason      *string `json:"reason,omitempty"`
}

type AdminNewsletterDispatchPayload struct {
	Success   bool                                   `json:"success"`
	Message   string                                 `json:"message"`
	Timestamp time.Time                              `json:"timestamp"`
	Results   []*AdminNewsletterDispatchLocaleResult `json:"results"`
}

type AdminNewsletterSubscriber struct {
	Email          string                          `json:"email"`
	Locale         string                          `json:"locale"`
	Status         AdminNewsletterSubscriberStatus `json:"status"`
	Tags           []string                        `json:"tags"`
	FormName       *string                         `json:"formName,omitempty"`
	Source         *string                         `json:"source,omitempty"`
	UpdatedAt      *time.Time                      `json:"updatedAt,omitempty"`
	CreatedAt      *time.Time                      `json:"createdAt,omitempty"`
	ConfirmedAt    *time.Time                      `json:"confirmedAt,omitempty"`
	UnsubscribedAt *time.Time                      `json:"unsubscribedAt,omitempty"`
}

type AdminNewsletterSubscriberFilterInput struct {
	Locale *string                          `json:"locale,omitempty"`
	Status *AdminNewsletterSubscriberStatus `json:"status,omitempty"`
	Query  *string                          `json:"query,omitempty"`
	Page   *int                             `json:"page,omitempty"`
	Size   *int                             `json:"size,omitempty"`
}

type AdminNewsletterSubscriberListPayload struct {
	Items []*AdminNewsletterSubscriber `json:"items"`
	Total int                          `json:"total"`
	Page  int                          `json:"page"`
	Size  int                          `json:"size"`
}

type AdminNewsletterTestSendPayload struct {
	Success   bool      `json:"success"`
	Message   string    `json:"message"`
	Timestamp time.Time `json:"timestamp"`
	Email     string    `json:"email"`
	Locale    string    `json:"locale"`
	ItemKey   string    `json:"itemKey"`
	PostTitle *string   `json:"postTitle,omitempty"`
}

type AdminPasswordChangePayload struct {
	Success bool `json:"success"`
}

type AdminQuery struct {
}

type AdminRequestEmailChangeInput struct {
	NewEmail        string  `json:"newEmail"`
	CurrentPassword string  `json:"currentPassword"`
	Locale          *string `json:"locale,omitempty"`
}

type AdminSendTestNewsletterInput struct {
	Email   string `json:"email"`
	Locale  string `json:"locale"`
	ItemKey string `json:"itemKey"`
}

type AdminSession struct {
	ID             string    `json:"id"`
	Device         string    `json:"device"`
	IPAddress      string    `json:"ipAddress"`
	CountryCode    string    `json:"countryCode"`
	LastActivityAt time.Time `json:"lastActivityAt"`
	CreatedAt      time.Time `json:"createdAt"`
	ExpiresAt      time.Time `json:"expiresAt"`
	Persistent     bool      `json:"persistent"`
	Current        bool      `json:"current"`
}

type AdminSessionRevokePayload struct {
	Success bool `json:"success"`
}

type AdminStartGithubConnectInput struct {
	Locale *string `json:"locale,omitempty"`
}

type AdminStartGoogleConnectInput struct {
	Locale *string `json:"locale,omitempty"`
}

type AdminUpdateCommentStatusInput struct {
	CommentID string             `json:"commentId"`
	Status    AdminCommentStatus `json:"status"`
}

type AdminUpdateContentPostContentInput struct {
	Locale  string `json:"locale"`
	ID      string `json:"id"`
	Content string `json:"content"`
}

type AdminUpdateContentPostMetadataInput struct {
	Locale        string   `json:"locale"`
	ID            string   `json:"id"`
	Title         *string  `json:"title,omitempty"`
	Summary       *string  `json:"summary,omitempty"`
	Thumbnail     *string  `json:"thumbnail,omitempty"`
	PublishedDate *string  `json:"publishedDate,omitempty"`
	UpdatedDate   *string  `json:"updatedDate,omitempty"`
	CategoryID    *string  `json:"categoryId,omitempty"`
	TopicIds      []string `json:"topicIds"`
}

type AdminUpdateErrorMessageInput struct {
	Key     *AdminErrorMessageKeyInput `json:"key"`
	Message string                     `json:"message"`
}

type AdminUpdateNewsletterSubscriberStatusInput struct {
	Email  string                          `json:"email"`
	Status AdminNewsletterSubscriberStatus `json:"status"`
}

type AdminUser struct {
	ID                    string     `json:"id"`
	Name                  *string    `json:"name,omitempty"`
	Username              *string    `json:"username,omitempty"`
	AvatarURL             *string    `json:"avatarUrl,omitempty"`
	Email                 string     `json:"email"`
	PendingEmail          *string    `json:"pendingEmail,omitempty"`
	PendingEmailExpiresAt *time.Time `json:"pendingEmailExpiresAt,omitempty"`
	GoogleLinked          bool       `json:"googleLinked"`
	GoogleEmail           *string    `json:"googleEmail,omitempty"`
	GoogleLinkedAt        *time.Time `json:"googleLinkedAt,omitempty"`
	GithubLinked          bool       `json:"githubLinked"`
	GithubEmail           *string    `json:"githubEmail,omitempty"`
	GithubLinkedAt        *time.Time `json:"githubLinkedAt,omitempty"`
	Roles                 []string   `json:"roles"`
}

type AdminCommentStatus string

const (
	AdminCommentStatusPending  AdminCommentStatus = "PENDING"
	AdminCommentStatusApproved AdminCommentStatus = "APPROVED"
	AdminCommentStatusRejected AdminCommentStatus = "REJECTED"
	AdminCommentStatusSpam     AdminCommentStatus = "SPAM"
)

var AllAdminCommentStatus = []AdminCommentStatus{
	AdminCommentStatusPending,
	AdminCommentStatusApproved,
	AdminCommentStatusRejected,
	AdminCommentStatusSpam,
}

func (e AdminCommentStatus) IsValid() bool {
	switch e {
	case AdminCommentStatusPending, AdminCommentStatusApproved, AdminCommentStatusRejected, AdminCommentStatusSpam:
		return true
	}
	return false
}

func (e AdminCommentStatus) String() string {
	return string(e)
}

func (e *AdminCommentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AdminCommentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AdminCommentStatus", str)
	}
	return nil
}

func (e AdminCommentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AdminCommentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AdminCommentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AdminNewsletterSubscriberStatus string

const (
	AdminNewsletterSubscriberStatusPending      AdminNewsletterSubscriberStatus = "PENDING"
	AdminNewsletterSubscriberStatusActive       AdminNewsletterSubscriberStatus = "ACTIVE"
	AdminNewsletterSubscriberStatusUnsubscribed AdminNewsletterSubscriberStatus = "UNSUBSCRIBED"
)

var AllAdminNewsletterSubscriberStatus = []AdminNewsletterSubscriberStatus{
	AdminNewsletterSubscriberStatusPending,
	AdminNewsletterSubscriberStatusActive,
	AdminNewsletterSubscriberStatusUnsubscribed,
}

func (e AdminNewsletterSubscriberStatus) IsValid() bool {
	switch e {
	case AdminNewsletterSubscriberStatusPending, AdminNewsletterSubscriberStatusActive, AdminNewsletterSubscriberStatusUnsubscribed:
		return true
	}
	return false
}

func (e AdminNewsletterSubscriberStatus) String() string {
	return string(e)
}

func (e *AdminNewsletterSubscriberStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AdminNewsletterSubscriberStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AdminNewsletterSubscriberStatus", str)
	}
	return nil
}

func (e AdminNewsletterSubscriberStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AdminNewsletterSubscriberStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AdminNewsletterSubscriberStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
