// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"suaybsimsek.com/blog-api/pkg/graphql/scalars"
)

type AdminAccountDeletePayload struct {
	Success bool `json:"success"`
}

type AdminAuthPayload struct {
	Success bool       `json:"success"`
	User    *AdminUser `json:"user,omitempty"`
}

type AdminBulkCommentMutationPayload struct {
	SuccessCount int `json:"successCount"`
}

type AdminBulkDeleteCommentsInput struct {
	CommentIds []string `json:"commentIds"`
}

type AdminBulkUpdateCommentStatusInput struct {
	CommentIds []string           `json:"commentIds"`
	Status     AdminCommentStatus `json:"status"`
}

type AdminChangeAvatarInput struct {
	AvatarURL *scalars.URL `json:"avatarUrl,omitempty"`
}

type AdminChangeNameInput struct {
	Name string `json:"name"`
}

type AdminChangePasswordInput struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
	ConfirmPassword string `json:"confirmPassword"`
}

type AdminChangeUsernameInput struct {
	NewUsername string `json:"newUsername"`
}

type AdminComment struct {
	ID          string             `json:"id"`
	PostID      string             `json:"postId"`
	PostTitle   string             `json:"postTitle"`
	ParentID    *string            `json:"parentId,omitempty"`
	AuthorName  string             `json:"authorName"`
	AuthorEmail scalars.Email      `json:"authorEmail"`
	Content     string             `json:"content"`
	Status      AdminCommentStatus `json:"status"`
	CreatedAt   time.Time          `json:"createdAt"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

type AdminCommentFilterInput struct {
	Status *AdminCommentStatus `json:"status,omitempty"`
	PostID *string             `json:"postId,omitempty"`
	Query  *string             `json:"query,omitempty"`
	Page   *int                `json:"page,omitempty"`
	Size   *int                `json:"size,omitempty"`
}

type AdminCommentListPayload struct {
	Items []*AdminComment `json:"items"`
	Total int             `json:"total"`
	Page  int             `json:"page"`
	Size  int             `json:"size"`
}

type AdminConfirmPasswordResetInput struct {
	Token           string          `json:"token"`
	NewPassword     string          `json:"newPassword"`
	ConfirmPassword string          `json:"confirmPassword"`
	Locale          *scalars.Locale `json:"locale,omitempty"`
}

type AdminContentCategory struct {
	Locale    scalars.Locale `json:"locale"`
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Color     string         `json:"color"`
	Icon      *string        `json:"icon,omitempty"`
	Link      *scalars.URL   `json:"link,omitempty"`
	UpdatedAt *time.Time     `json:"updatedAt,omitempty"`
}

type AdminContentCategoryGroup struct {
	ID        string                `json:"id"`
	Preferred *AdminContentCategory `json:"preferred"`
	En        *AdminContentCategory `json:"en,omitempty"`
	Tr        *AdminContentCategory `json:"tr,omitempty"`
}

type AdminContentCategoryInput struct {
	Locale scalars.Locale `json:"locale"`
	ID     string         `json:"id"`
	Name   string         `json:"name"`
	Color  string         `json:"color"`
	Icon   *string        `json:"icon,omitempty"`
	Link   *scalars.URL   `json:"link,omitempty"`
}

type AdminContentCategoryListPayload struct {
	Items []*AdminContentCategoryGroup `json:"items"`
	Total int                          `json:"total"`
	Page  int                          `json:"page"`
	Size  int                          `json:"size"`
}

type AdminContentEntityKeyInput struct {
	Locale scalars.Locale `json:"locale"`
	ID     string         `json:"id"`
}

type AdminContentPost struct {
	Locale           scalars.Locale         `json:"locale"`
	ID               string                 `json:"id"`
	Title            string                 `json:"title"`
	Summary          *string                `json:"summary,omitempty"`
	Content          *string                `json:"content,omitempty"`
	ContentMode      *AdminContentMode      `json:"contentMode,omitempty"`
	Thumbnail        *string                `json:"thumbnail,omitempty"`
	Source           ContentSource          `json:"source"`
	PublishedDate    scalars.Date           `json:"publishedDate"`
	UpdatedDate      *scalars.Date          `json:"updatedDate,omitempty"`
	CategoryID       *string                `json:"categoryId,omitempty"`
	CategoryName     *string                `json:"categoryName,omitempty"`
	TopicIds         []string               `json:"topicIds"`
	TopicNames       []string               `json:"topicNames"`
	ReadingTimeMin   int                    `json:"readingTimeMin"`
	Status           AdminContentPostStatus `json:"status"`
	ScheduledAt      *time.Time             `json:"scheduledAt,omitempty"`
	ContentUpdatedAt *time.Time             `json:"contentUpdatedAt,omitempty"`
	UpdatedAt        *time.Time             `json:"updatedAt,omitempty"`
	RevisionCount    int                    `json:"revisionCount"`
	LatestRevisionAt *time.Time             `json:"latestRevisionAt,omitempty"`
	ViewCount        int                    `json:"viewCount"`
	LikeCount        int                    `json:"likeCount"`
	CommentCount     int                    `json:"commentCount"`
}

type AdminContentPostFilterInput struct {
	Locale          *scalars.Locale `json:"locale,omitempty"`
	PreferredLocale *scalars.Locale `json:"preferredLocale,omitempty"`
	Source          *ContentSource  `json:"source,omitempty"`
	Query           *string         `json:"query,omitempty"`
	CategoryID      *string         `json:"categoryId,omitempty"`
	TopicID         *string         `json:"topicId,omitempty"`
	Page            *int            `json:"page,omitempty"`
	Size            *int            `json:"size,omitempty"`
}

type AdminContentPostGroup struct {
	ID        string            `json:"id"`
	Source    ContentSource     `json:"source"`
	Preferred *AdminContentPost `json:"preferred"`
	En        *AdminContentPost `json:"en,omitempty"`
	Tr        *AdminContentPost `json:"tr,omitempty"`
}

type AdminContentPostListPayload struct {
	Items []*AdminContentPostGroup `json:"items"`
	Total int                      `json:"total"`
	Page  int                      `json:"page"`
	Size  int                      `json:"size"`
}

type AdminContentPostRevision struct {
	ID             string                 `json:"id"`
	Locale         scalars.Locale         `json:"locale"`
	PostID         string                 `json:"postId"`
	RevisionNumber int                    `json:"revisionNumber"`
	Title          string                 `json:"title"`
	Summary        *string                `json:"summary,omitempty"`
	Content        *string                `json:"content,omitempty"`
	ContentMode    *AdminContentMode      `json:"contentMode,omitempty"`
	Thumbnail      *string                `json:"thumbnail,omitempty"`
	PublishedDate  scalars.Date           `json:"publishedDate"`
	UpdatedDate    *scalars.Date          `json:"updatedDate,omitempty"`
	CategoryID     *string                `json:"categoryId,omitempty"`
	CategoryName   *string                `json:"categoryName,omitempty"`
	TopicIds       []string               `json:"topicIds"`
	TopicNames     []string               `json:"topicNames"`
	ReadingTimeMin int                    `json:"readingTimeMin"`
	Status         AdminContentPostStatus `json:"status"`
	ScheduledAt    *time.Time             `json:"scheduledAt,omitempty"`
	CreatedAt      time.Time              `json:"createdAt"`
}

type AdminContentPostRevisionListPayload struct {
	Items []*AdminContentPostRevision `json:"items"`
	Total int                         `json:"total"`
	Page  int                         `json:"page"`
	Size  int                         `json:"size"`
}

type AdminContentTaxonomyFilterInput struct {
	Locale          *scalars.Locale `json:"locale,omitempty"`
	PreferredLocale *scalars.Locale `json:"preferredLocale,omitempty"`
	Query           *string         `json:"query,omitempty"`
	Page            *int            `json:"page,omitempty"`
	Size            *int            `json:"size,omitempty"`
}

type AdminContentTopic struct {
	Locale    scalars.Locale `json:"locale"`
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Color     string         `json:"color"`
	Link      *scalars.URL   `json:"link,omitempty"`
	UpdatedAt *time.Time     `json:"updatedAt,omitempty"`
}

type AdminContentTopicGroup struct {
	ID        string             `json:"id"`
	Preferred *AdminContentTopic `json:"preferred"`
	En        *AdminContentTopic `json:"en,omitempty"`
	Tr        *AdminContentTopic `json:"tr,omitempty"`
}

type AdminContentTopicInput struct {
	Locale scalars.Locale `json:"locale"`
	ID     string         `json:"id"`
	Name   string         `json:"name"`
	Color  string         `json:"color"`
	Link   *scalars.URL   `json:"link,omitempty"`
}

type AdminContentTopicListPayload struct {
	Items []*AdminContentTopicGroup `json:"items"`
	Total int                       `json:"total"`
	Page  int                       `json:"page"`
	Size  int                       `json:"size"`
}

type AdminCreateErrorMessageInput struct {
	Key     *AdminErrorMessageKeyInput `json:"key"`
	Message string                     `json:"message"`
}

type AdminDashboard struct {
	TotalPosts       int                          `json:"totalPosts"`
	TotalSubscribers int                          `json:"totalSubscribers"`
	TopViewedPosts   []*AdminDashboardPost        `json:"topViewedPosts"`
	TopLikedPosts    []*AdminDashboardPost        `json:"topLikedPosts"`
	ContentHealth    *AdminDashboardContentHealth `json:"contentHealth"`
}

type AdminDashboardCategory struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Count int    `json:"count"`
}

type AdminDashboardContentHealth struct {
	LocalePairCoverage  int                          `json:"localePairCoverage"`
	MissingTranslations int                          `json:"missingTranslations"`
	MissingThumbnails   int                          `json:"missingThumbnails"`
	LatestUpdatedPosts  []*AdminDashboardUpdatedPost `json:"latestUpdatedPosts"`
	DominantCategory    *AdminDashboardCategory      `json:"dominantCategory,omitempty"`
}

type AdminDashboardPost struct {
	PostID        string         `json:"postId"`
	Title         string         `json:"title"`
	Locale        scalars.Locale `json:"locale"`
	PublishedDate scalars.Date   `json:"publishedDate"`
	Hits          int            `json:"hits"`
	Likes         int            `json:"likes"`
}

type AdminDashboardUpdatedPost struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Date     string `json:"date"`
	Category string `json:"category"`
}

type AdminDeleteAccountInput struct {
	CurrentPassword string `json:"currentPassword"`
}

type AdminDeleteCommentInput struct {
	CommentID string `json:"commentId"`
}

type AdminDeleteNewsletterSubscriberInput struct {
	Email scalars.Email `json:"email"`
}

type AdminDeletePayload struct {
	Success bool `json:"success"`
}

type AdminEmailChangeConfirmPayload struct {
	Status string         `json:"status"`
	Locale scalars.Locale `json:"locale"`
}

type AdminEmailChangeRequestPayload struct {
	Success      bool          `json:"success"`
	PendingEmail scalars.Email `json:"pendingEmail"`
	ExpiresAt    time.Time     `json:"expiresAt"`
}

type AdminErrorMessage struct {
	Scope     string         `json:"scope"`
	Locale    scalars.Locale `json:"locale"`
	Code      string         `json:"code"`
	Message   string         `json:"message"`
	UpdatedAt *time.Time     `json:"updatedAt,omitempty"`
}

type AdminErrorMessageAuditLog struct {
	ID          string           `json:"id"`
	ActorID     string           `json:"actorId"`
	ActorEmail  scalars.Email    `json:"actorEmail"`
	Action      string           `json:"action"`
	Scope       string           `json:"scope"`
	Locale      scalars.Locale   `json:"locale"`
	Code        string           `json:"code"`
	BeforeValue string           `json:"beforeValue"`
	AfterValue  string           `json:"afterValue"`
	Status      AdminAuditStatus `json:"status"`
	FailureCode *string          `json:"failureCode,omitempty"`
	RequestID   *string          `json:"requestId,omitempty"`
	RemoteIP    *string          `json:"remoteIp,omitempty"`
	CountryCode *string          `json:"countryCode,omitempty"`
	UserAgent   *string          `json:"userAgent,omitempty"`
	CreatedAt   time.Time        `json:"createdAt"`
}

type AdminErrorMessageFilterInput struct {
	Locale *scalars.Locale `json:"locale,omitempty"`
	Code   *string         `json:"code,omitempty"`
	Query  *string         `json:"query,omitempty"`
	Page   *int            `json:"page,omitempty"`
	Size   *int            `json:"size,omitempty"`
}

type AdminErrorMessageKeyInput struct {
	Scope  *string        `json:"scope,omitempty"`
	Locale scalars.Locale `json:"locale"`
	Code   string         `json:"code"`
}

type AdminErrorMessageListPayload struct {
	Items []*AdminErrorMessage `json:"items"`
	Total int                  `json:"total"`
	Page  int                  `json:"page"`
	Size  int                  `json:"size"`
}

type AdminGithubAuthStatus struct {
	Enabled        bool `json:"enabled"`
	LoginAvailable bool `json:"loginAvailable"`
}

type AdminGithubConnectPayload struct {
	URL scalars.URL `json:"url"`
}

type AdminGithubDisconnectPayload struct {
	Success bool       `json:"success"`
	User    *AdminUser `json:"user,omitempty"`
}

type AdminGoogleAuthStatus struct {
	Enabled        bool `json:"enabled"`
	LoginAvailable bool `json:"loginAvailable"`
}

type AdminGoogleConnectPayload struct {
	URL scalars.URL `json:"url"`
}

type AdminGoogleDisconnectPayload struct {
	Success bool       `json:"success"`
	User    *AdminUser `json:"user,omitempty"`
}

type AdminLoginInput struct {
	Email      scalars.Email `json:"email"`
	Password   string        `json:"password"`
	RememberMe *bool         `json:"rememberMe,omitempty"`
}

type AdminLogoutPayload struct {
	Success bool `json:"success"`
}

type AdminMe struct {
	Authenticated bool       `json:"authenticated"`
	User          *AdminUser `json:"user,omitempty"`
}

type AdminMediaLibraryFilterInput struct {
	Query *string                    `json:"query,omitempty"`
	Kind  *AdminMediaLibraryItemKind `json:"kind,omitempty"`
	Sort  *AdminMediaLibrarySort     `json:"sort,omitempty"`
	Page  *int                       `json:"page,omitempty"`
	Size  *int                       `json:"size,omitempty"`
}

type AdminMediaLibraryItem struct {
	ID          string                    `json:"id"`
	Kind        AdminMediaLibraryItemKind `json:"kind"`
	Name        string                    `json:"name"`
	Value       string                    `json:"value"`
	PreviewURL  string                    `json:"previewUrl"`
	ContentType *string                   `json:"contentType,omitempty"`
	Width       *int                      `json:"width,omitempty"`
	Height      *int                      `json:"height,omitempty"`
	SizeBytes   int                       `json:"sizeBytes"`
	UsageCount  int                       `json:"usageCount"`
	CreatedAt   *time.Time                `json:"createdAt,omitempty"`
	UpdatedAt   *time.Time                `json:"updatedAt,omitempty"`
}

type AdminMediaLibraryListPayload struct {
	Items []*AdminMediaLibraryItem `json:"items"`
	Total int                      `json:"total"`
	Page  int                      `json:"page"`
	Size  int                      `json:"size"`
}

type AdminMutation struct {
}

type AdminNewsletterCampaign struct {
	Locale      scalars.Locale                `json:"locale"`
	ItemKey     string                        `json:"itemKey"`
	Title       string                        `json:"title"`
	Summary     *string                       `json:"summary,omitempty"`
	Link        *scalars.URL                  `json:"link,omitempty"`
	PubDate     *scalars.Date                 `json:"pubDate,omitempty"`
	RssURL      *scalars.URL                  `json:"rssUrl,omitempty"`
	Status      AdminNewsletterCampaignStatus `json:"status"`
	SentCount   int                           `json:"sentCount"`
	FailedCount int                           `json:"failedCount"`
	LastRunAt   *time.Time                    `json:"lastRunAt,omitempty"`
	UpdatedAt   *time.Time                    `json:"updatedAt,omitempty"`
	CreatedAt   *time.Time                    `json:"createdAt,omitempty"`
}

type AdminNewsletterCampaignFilterInput struct {
	Locale *scalars.Locale                `json:"locale,omitempty"`
	Status *AdminNewsletterCampaignStatus `json:"status,omitempty"`
	Query  *string                        `json:"query,omitempty"`
	Page   *int                           `json:"page,omitempty"`
	Size   *int                           `json:"size,omitempty"`
}

type AdminNewsletterCampaignListPayload struct {
	Items []*AdminNewsletterCampaign `json:"items"`
	Total int                        `json:"total"`
	Page  int                        `json:"page"`
	Size  int                        `json:"size"`
}

type AdminNewsletterDeliveryFailure struct {
	Locale        scalars.Locale                       `json:"locale"`
	ItemKey       string                               `json:"itemKey"`
	Email         scalars.Email                        `json:"email"`
	Status        AdminNewsletterDeliveryFailureStatus `json:"status"`
	LastError     *string                              `json:"lastError,omitempty"`
	LastAttemptAt *time.Time                           `json:"lastAttemptAt,omitempty"`
	UpdatedAt     *time.Time                           `json:"updatedAt,omitempty"`
	CreatedAt     *time.Time                           `json:"createdAt,omitempty"`
}

type AdminNewsletterDeliveryFailureFilterInput struct {
	Locale  scalars.Locale `json:"locale"`
	ItemKey string         `json:"itemKey"`
	Page    *int           `json:"page,omitempty"`
	Size    *int           `json:"size,omitempty"`
}

type AdminNewsletterDeliveryFailureListPayload struct {
	Items []*AdminNewsletterDeliveryFailure `json:"items"`
	Total int                               `json:"total"`
	Page  int                               `json:"page"`
	Size  int                               `json:"size"`
}

type AdminNewsletterDispatchLocaleResult struct {
	Locale      scalars.Locale `json:"locale"`
	RssURL      *scalars.URL   `json:"rssUrl,omitempty"`
	ItemKey     *string        `json:"itemKey,omitempty"`
	PostTitle   *string        `json:"postTitle,omitempty"`
	SentCount   int            `json:"sentCount"`
	FailedCount int            `json:"failedCount"`
	Skipped     bool           `json:"skipped"`
	Reason      *string        `json:"reason,omitempty"`
}

type AdminNewsletterDispatchPayload struct {
	Success   bool                                   `json:"success"`
	Message   string                                 `json:"message"`
	Timestamp time.Time                              `json:"timestamp"`
	Results   []*AdminNewsletterDispatchLocaleResult `json:"results"`
}

type AdminNewsletterSubscriber struct {
	Email          scalars.Email                   `json:"email"`
	Locale         scalars.Locale                  `json:"locale"`
	Status         AdminNewsletterSubscriberStatus `json:"status"`
	Tags           []string                        `json:"tags"`
	FormName       *string                         `json:"formName,omitempty"`
	Source         *string                         `json:"source,omitempty"`
	UpdatedAt      *time.Time                      `json:"updatedAt,omitempty"`
	CreatedAt      *time.Time                      `json:"createdAt,omitempty"`
	ConfirmedAt    *time.Time                      `json:"confirmedAt,omitempty"`
	UnsubscribedAt *time.Time                      `json:"unsubscribedAt,omitempty"`
}

type AdminNewsletterSubscriberFilterInput struct {
	Locale *scalars.Locale                  `json:"locale,omitempty"`
	Status *AdminNewsletterSubscriberStatus `json:"status,omitempty"`
	Query  *string                          `json:"query,omitempty"`
	Page   *int                             `json:"page,omitempty"`
	Size   *int                             `json:"size,omitempty"`
}

type AdminNewsletterSubscriberListPayload struct {
	Items []*AdminNewsletterSubscriber `json:"items"`
	Total int                          `json:"total"`
	Page  int                          `json:"page"`
	Size  int                          `json:"size"`
}

type AdminNewsletterTestSendPayload struct {
	Success   bool           `json:"success"`
	Message   string         `json:"message"`
	Timestamp time.Time      `json:"timestamp"`
	Email     scalars.Email  `json:"email"`
	Locale    scalars.Locale `json:"locale"`
	ItemKey   string         `json:"itemKey"`
	PostTitle *string        `json:"postTitle,omitempty"`
}

type AdminPasswordChangePayload struct {
	Success bool `json:"success"`
}

type AdminPasswordResetConfirmPayload struct {
	Success bool           `json:"success"`
	Locale  scalars.Locale `json:"locale"`
}

type AdminPasswordResetRequestPayload struct {
	Success bool `json:"success"`
}

type AdminPasswordResetValidationPayload struct {
	Status string         `json:"status"`
	Locale scalars.Locale `json:"locale"`
}

type AdminQuery struct {
}

type AdminRequestEmailChangeInput struct {
	NewEmail        scalars.Email   `json:"newEmail"`
	CurrentPassword string          `json:"currentPassword"`
	Locale          *scalars.Locale `json:"locale,omitempty"`
}

type AdminRequestPasswordResetInput struct {
	Email  scalars.Email   `json:"email"`
	Locale *scalars.Locale `json:"locale,omitempty"`
}

type AdminRestoreContentPostRevisionInput struct {
	Locale     scalars.Locale `json:"locale"`
	PostID     string         `json:"postId"`
	RevisionID string         `json:"revisionId"`
}

type AdminSendTestNewsletterInput struct {
	Email   scalars.Email  `json:"email"`
	Locale  scalars.Locale `json:"locale"`
	ItemKey string         `json:"itemKey"`
}

type AdminSession struct {
	ID             string    `json:"id"`
	Device         string    `json:"device"`
	IPAddress      string    `json:"ipAddress"`
	CountryCode    string    `json:"countryCode"`
	LastActivityAt time.Time `json:"lastActivityAt"`
	CreatedAt      time.Time `json:"createdAt"`
	ExpiresAt      time.Time `json:"expiresAt"`
	Persistent     bool      `json:"persistent"`
	Current        bool      `json:"current"`
}

type AdminSessionRevokePayload struct {
	Success bool `json:"success"`
}

type AdminStartGithubConnectInput struct {
	Locale *scalars.Locale `json:"locale,omitempty"`
}

type AdminStartGoogleConnectInput struct {
	Locale *scalars.Locale `json:"locale,omitempty"`
}

type AdminUpdateCommentStatusInput struct {
	CommentID string             `json:"commentId"`
	Status    AdminCommentStatus `json:"status"`
}

type AdminUpdateContentPostContentInput struct {
	Locale  scalars.Locale `json:"locale"`
	ID      string         `json:"id"`
	Content string         `json:"content"`
}

type AdminUpdateContentPostMetadataInput struct {
	Locale        scalars.Locale          `json:"locale"`
	ID            string                  `json:"id"`
	Title         *string                 `json:"title,omitempty"`
	Summary       *string                 `json:"summary,omitempty"`
	Thumbnail     *string                 `json:"thumbnail,omitempty"`
	PublishedDate *scalars.Date           `json:"publishedDate,omitempty"`
	UpdatedDate   *scalars.Date           `json:"updatedDate,omitempty"`
	Status        *AdminContentPostStatus `json:"status,omitempty"`
	ScheduledAt   *time.Time              `json:"scheduledAt,omitempty"`
	CategoryID    *string                 `json:"categoryId,omitempty"`
	TopicIds      []string                `json:"topicIds"`
}

type AdminUpdateErrorMessageInput struct {
	Key     *AdminErrorMessageKeyInput `json:"key"`
	Message string                     `json:"message"`
}

type AdminUpdateNewsletterSubscriberStatusInput struct {
	Email  scalars.Email                   `json:"email"`
	Status AdminNewsletterSubscriberStatus `json:"status"`
}

type AdminUploadMediaAssetInput struct {
	FileName string `json:"fileName"`
	DataURL  string `json:"dataUrl"`
}

type AdminUser struct {
	ID                    string         `json:"id"`
	Name                  *string        `json:"name,omitempty"`
	Username              *string        `json:"username,omitempty"`
	AvatarURL             *scalars.URL   `json:"avatarUrl,omitempty"`
	Email                 scalars.Email  `json:"email"`
	PendingEmail          *scalars.Email `json:"pendingEmail,omitempty"`
	PendingEmailExpiresAt *time.Time     `json:"pendingEmailExpiresAt,omitempty"`
	GoogleLinked          bool           `json:"googleLinked"`
	GoogleEmail           *scalars.Email `json:"googleEmail,omitempty"`
	GoogleLinkedAt        *time.Time     `json:"googleLinkedAt,omitempty"`
	GithubLinked          bool           `json:"githubLinked"`
	GithubEmail           *scalars.Email `json:"githubEmail,omitempty"`
	GithubLinkedAt        *time.Time     `json:"githubLinkedAt,omitempty"`
	Roles                 []string       `json:"roles"`
}

type AdminAuditStatus string

const (
	AdminAuditStatusSuccess AdminAuditStatus = "success"
)

var AllAdminAuditStatus = []AdminAuditStatus{
	AdminAuditStatusSuccess,
}

func (e AdminAuditStatus) IsValid() bool {
	switch e {
	case AdminAuditStatusSuccess:
		return true
	}
	return false
}

func (e AdminAuditStatus) String() string {
	return string(e)
}

func (e *AdminAuditStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AdminAuditStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AdminAuditStatus", str)
	}
	return nil
}

func (e AdminAuditStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AdminAuditStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AdminAuditStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AdminCommentStatus string

const (
	AdminCommentStatusPending  AdminCommentStatus = "PENDING"
	AdminCommentStatusApproved AdminCommentStatus = "APPROVED"
	AdminCommentStatusRejected AdminCommentStatus = "REJECTED"
	AdminCommentStatusSpam     AdminCommentStatus = "SPAM"
)

var AllAdminCommentStatus = []AdminCommentStatus{
	AdminCommentStatusPending,
	AdminCommentStatusApproved,
	AdminCommentStatusRejected,
	AdminCommentStatusSpam,
}

func (e AdminCommentStatus) IsValid() bool {
	switch e {
	case AdminCommentStatusPending, AdminCommentStatusApproved, AdminCommentStatusRejected, AdminCommentStatusSpam:
		return true
	}
	return false
}

func (e AdminCommentStatus) String() string {
	return string(e)
}

func (e *AdminCommentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AdminCommentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AdminCommentStatus", str)
	}
	return nil
}

func (e AdminCommentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AdminCommentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AdminCommentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AdminContentMode string

const (
	AdminContentModeMarkdown AdminContentMode = "markdown"
	AdminContentModeAdmin    AdminContentMode = "admin"
)

var AllAdminContentMode = []AdminContentMode{
	AdminContentModeMarkdown,
	AdminContentModeAdmin,
}

func (e AdminContentMode) IsValid() bool {
	switch e {
	case AdminContentModeMarkdown, AdminContentModeAdmin:
		return true
	}
	return false
}

func (e AdminContentMode) String() string {
	return string(e)
}

func (e *AdminContentMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AdminContentMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AdminContentMode", str)
	}
	return nil
}

func (e AdminContentMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AdminContentMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AdminContentMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AdminContentPostStatus string

const (
	AdminContentPostStatusDraft     AdminContentPostStatus = "DRAFT"
	AdminContentPostStatusScheduled AdminContentPostStatus = "SCHEDULED"
	AdminContentPostStatusPublished AdminContentPostStatus = "PUBLISHED"
)

var AllAdminContentPostStatus = []AdminContentPostStatus{
	AdminContentPostStatusDraft,
	AdminContentPostStatusScheduled,
	AdminContentPostStatusPublished,
}

func (e AdminContentPostStatus) IsValid() bool {
	switch e {
	case AdminContentPostStatusDraft, AdminContentPostStatusScheduled, AdminContentPostStatusPublished:
		return true
	}
	return false
}

func (e AdminContentPostStatus) String() string {
	return string(e)
}

func (e *AdminContentPostStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AdminContentPostStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AdminContentPostStatus", str)
	}
	return nil
}

func (e AdminContentPostStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AdminContentPostStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AdminContentPostStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AdminMediaLibraryItemKind string

const (
	AdminMediaLibraryItemKindUploaded  AdminMediaLibraryItemKind = "UPLOADED"
	AdminMediaLibraryItemKindReference AdminMediaLibraryItemKind = "REFERENCE"
)

var AllAdminMediaLibraryItemKind = []AdminMediaLibraryItemKind{
	AdminMediaLibraryItemKindUploaded,
	AdminMediaLibraryItemKindReference,
}

func (e AdminMediaLibraryItemKind) IsValid() bool {
	switch e {
	case AdminMediaLibraryItemKindUploaded, AdminMediaLibraryItemKindReference:
		return true
	}
	return false
}

func (e AdminMediaLibraryItemKind) String() string {
	return string(e)
}

func (e *AdminMediaLibraryItemKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AdminMediaLibraryItemKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AdminMediaLibraryItemKind", str)
	}
	return nil
}

func (e AdminMediaLibraryItemKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AdminMediaLibraryItemKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AdminMediaLibraryItemKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AdminMediaLibrarySort string

const (
	AdminMediaLibrarySortRecent AdminMediaLibrarySort = "RECENT"
	AdminMediaLibrarySortName   AdminMediaLibrarySort = "NAME"
	AdminMediaLibrarySortSize   AdminMediaLibrarySort = "SIZE"
	AdminMediaLibrarySortUsage  AdminMediaLibrarySort = "USAGE"
)

var AllAdminMediaLibrarySort = []AdminMediaLibrarySort{
	AdminMediaLibrarySortRecent,
	AdminMediaLibrarySortName,
	AdminMediaLibrarySortSize,
	AdminMediaLibrarySortUsage,
}

func (e AdminMediaLibrarySort) IsValid() bool {
	switch e {
	case AdminMediaLibrarySortRecent, AdminMediaLibrarySortName, AdminMediaLibrarySortSize, AdminMediaLibrarySortUsage:
		return true
	}
	return false
}

func (e AdminMediaLibrarySort) String() string {
	return string(e)
}

func (e *AdminMediaLibrarySort) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AdminMediaLibrarySort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AdminMediaLibrarySort", str)
	}
	return nil
}

func (e AdminMediaLibrarySort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AdminMediaLibrarySort) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AdminMediaLibrarySort) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AdminNewsletterCampaignStatus string

const (
	AdminNewsletterCampaignStatusProcessing AdminNewsletterCampaignStatus = "processing"
	AdminNewsletterCampaignStatusPartial    AdminNewsletterCampaignStatus = "partial"
	AdminNewsletterCampaignStatusSent       AdminNewsletterCampaignStatus = "sent"
)

var AllAdminNewsletterCampaignStatus = []AdminNewsletterCampaignStatus{
	AdminNewsletterCampaignStatusProcessing,
	AdminNewsletterCampaignStatusPartial,
	AdminNewsletterCampaignStatusSent,
}

func (e AdminNewsletterCampaignStatus) IsValid() bool {
	switch e {
	case AdminNewsletterCampaignStatusProcessing, AdminNewsletterCampaignStatusPartial, AdminNewsletterCampaignStatusSent:
		return true
	}
	return false
}

func (e AdminNewsletterCampaignStatus) String() string {
	return string(e)
}

func (e *AdminNewsletterCampaignStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AdminNewsletterCampaignStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AdminNewsletterCampaignStatus", str)
	}
	return nil
}

func (e AdminNewsletterCampaignStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AdminNewsletterCampaignStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AdminNewsletterCampaignStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AdminNewsletterDeliveryFailureStatus string

const (
	AdminNewsletterDeliveryFailureStatusFailed AdminNewsletterDeliveryFailureStatus = "failed"
)

var AllAdminNewsletterDeliveryFailureStatus = []AdminNewsletterDeliveryFailureStatus{
	AdminNewsletterDeliveryFailureStatusFailed,
}

func (e AdminNewsletterDeliveryFailureStatus) IsValid() bool {
	switch e {
	case AdminNewsletterDeliveryFailureStatusFailed:
		return true
	}
	return false
}

func (e AdminNewsletterDeliveryFailureStatus) String() string {
	return string(e)
}

func (e *AdminNewsletterDeliveryFailureStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AdminNewsletterDeliveryFailureStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AdminNewsletterDeliveryFailureStatus", str)
	}
	return nil
}

func (e AdminNewsletterDeliveryFailureStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AdminNewsletterDeliveryFailureStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AdminNewsletterDeliveryFailureStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AdminNewsletterSubscriberStatus string

const (
	AdminNewsletterSubscriberStatusPending      AdminNewsletterSubscriberStatus = "PENDING"
	AdminNewsletterSubscriberStatusActive       AdminNewsletterSubscriberStatus = "ACTIVE"
	AdminNewsletterSubscriberStatusUnsubscribed AdminNewsletterSubscriberStatus = "UNSUBSCRIBED"
)

var AllAdminNewsletterSubscriberStatus = []AdminNewsletterSubscriberStatus{
	AdminNewsletterSubscriberStatusPending,
	AdminNewsletterSubscriberStatusActive,
	AdminNewsletterSubscriberStatusUnsubscribed,
}

func (e AdminNewsletterSubscriberStatus) IsValid() bool {
	switch e {
	case AdminNewsletterSubscriberStatusPending, AdminNewsletterSubscriberStatusActive, AdminNewsletterSubscriberStatusUnsubscribed:
		return true
	}
	return false
}

func (e AdminNewsletterSubscriberStatus) String() string {
	return string(e)
}

func (e *AdminNewsletterSubscriberStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AdminNewsletterSubscriberStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AdminNewsletterSubscriberStatus", str)
	}
	return nil
}

func (e AdminNewsletterSubscriberStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AdminNewsletterSubscriberStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AdminNewsletterSubscriberStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ContentSource string

const (
	ContentSourceBlog   ContentSource = "blog"
	ContentSourceMedium ContentSource = "medium"
)

var AllContentSource = []ContentSource{
	ContentSourceBlog,
	ContentSourceMedium,
}

func (e ContentSource) IsValid() bool {
	switch e {
	case ContentSourceBlog, ContentSourceMedium:
		return true
	}
	return false
}

func (e ContentSource) String() string {
	return string(e)
}

func (e *ContentSource) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ContentSource(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ContentSource", str)
	}
	return nil
}

func (e ContentSource) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ContentSource) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ContentSource) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
