root = "."
tmp_dir = ".air"

[build]
cmd = "go build -o ./.air/backend-app ./cmd/app"
entrypoint = ["./.air/backend-app"]
delay = 300
include_dir = ["api", "cmd", "internal", "pkg"]
exclude_file = ["golangci-lint-report.xml"]
exclude_dir = ["node_modules", "build", "coverage", ".air"]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
include_ext = ["go", "graphqls", "html", "tmpl", "tpl"]
include_file = [".air.toml", ".env.local", "go.mod", "go.sum", "gqlgen.yml"]
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true
