// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Mutation struct {
}

type NewsletterMutationResult struct {
	Status    string  `json:"status"`
	ForwardTo *string `json:"forwardTo,omitempty"`
}

type NewsletterResendInput struct {
	Locale string `json:"locale"`
	Email  string `json:"email"`
	Terms  bool   `json:"terms"`
}

type NewsletterSubscribeInput struct {
	Locale   string   `json:"locale"`
	Email    string   `json:"email"`
	Terms    bool     `json:"terms"`
	Tags     []string `json:"tags,omitempty"`
	FormName *string  `json:"formName,omitempty"`
}

type Post struct {
	ID            string        `json:"id"`
	Slug          string        `json:"slug"`
	Title         string        `json:"title"`
	Category      *PostCategory `json:"category,omitempty"`
	PublishedDate string        `json:"publishedDate"`
	UpdatedDate   *string       `json:"updatedDate,omitempty"`
	Summary       string        `json:"summary"`
	SearchText    string        `json:"searchText"`
	Thumbnail     *string       `json:"thumbnail,omitempty"`
	Topics        []*Topic      `json:"topics,omitempty"`
	ReadingTime   int           `json:"readingTime"`
	Source        *string       `json:"source,omitempty"`
	URL           *string       `json:"url,omitempty"`
}

type PostCategory struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type PostConnection struct {
	Status     string            `json:"status"`
	Locale     *string           `json:"locale,omitempty"`
	Nodes      []*Post           `json:"nodes"`
	Engagement []*PostEngagement `json:"engagement"`
	Total      int               `json:"total"`
	Page       int               `json:"page"`
	Size       int               `json:"size"`
	Sort       *string           `json:"sort,omitempty"`
}

type PostEngagement struct {
	PostID string `json:"postId"`
	Likes  int    `json:"likes"`
	Hits   int    `json:"hits"`
}

type PostMetricResult struct {
	Status string `json:"status"`
	PostID string `json:"postId"`
	Likes  *int   `json:"likes,omitempty"`
	Hits   *int   `json:"hits,omitempty"`
}

type PostResult struct {
	Status     string          `json:"status"`
	Locale     *string         `json:"locale,omitempty"`
	Node       *Post           `json:"node,omitempty"`
	Engagement *PostEngagement `json:"engagement,omitempty"`
}

type PostsQueryInput struct {
	Page     *int       `json:"page,omitempty"`
	Size     *int       `json:"size,omitempty"`
	Sort     *SortOrder `json:"sort,omitempty"`
	ScopeIds []string   `json:"scopeIds,omitempty"`
}

type Query struct {
}

type Topic struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Color string  `json:"color"`
	Link  *string `json:"link,omitempty"`
}

type SortOrder string

const (
	SortOrderAsc  SortOrder = "ASC"
	SortOrderDesc SortOrder = "DESC"
)

var AllSortOrder = []SortOrder{
	SortOrderAsc,
	SortOrderDesc,
}

func (e SortOrder) IsValid() bool {
	switch e {
	case SortOrderAsc, SortOrderDesc:
		return true
	}
	return false
}

func (e SortOrder) String() string {
	return string(e)
}

func (e *SortOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrder", str)
	}
	return nil
}

func (e SortOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
