{{- if and .Values.serviceAccount.create .Values.rbac.create }}
kind: RoleBinding
apiVersion: {{ include "blog.capabilities.rbac.apiVersion" . }}
metadata:
  name: {{ template "blog.fullname" . }}
  namespace: {{ include "blog.namespace" . | quote }}
  labels: {{- include "blog.labels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: blog
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "blog.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "blog.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "blog.serviceAccountName" . }}
    namespace: {{ include "blog.namespace" . | quote }}
{{- end }}
