package admingraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"net/http"
	"strings"
	"time"

	appconfig "suaybsimsek.com/blog-api/internal/config"
	"suaybsimsek.com/blog-api/internal/domain"
	"suaybsimsek.com/blog-api/internal/graphql/admin/model"
	appservice "suaybsimsek.com/blog-api/internal/service"
	"suaybsimsek.com/blog-api/pkg/apperrors"
	"suaybsimsek.com/blog-api/pkg/httpapi"
	"suaybsimsek.com/blog-api/pkg/httpauth"
)

// Me is the resolver for the me field.
func (r *adminQueryResolver) Me(ctx context.Context) (*model.AdminMe, error) {
	user := getAdminUser(ctx)
	if user == nil {
		return &model.AdminMe{Authenticated: false}, nil
	}

	return &model.AdminMe{
		Authenticated: true,
		User:          mapAdminUser(user),
	}, nil
}

// Dashboard is the resolver for the dashboard field.
func (r *adminQueryResolver) Dashboard(ctx context.Context) (*model.AdminDashboard, error) {
	if _, err := requireAdminUser(ctx); err != nil {
		return nil, err
	}

	payload, err := appservice.QueryAdminDashboard(ctx)
	if err != nil {
		return nil, err
	}

	return mapAdminDashboard(payload), nil
}

// ActiveSessions is the resolver for the activeSessions field.
func (r *adminQueryResolver) ActiveSessions(ctx context.Context) ([]*model.AdminSession, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	sessions, err := appservice.ListActiveAdminSessions(ctx, adminUser)
	if err != nil {
		return nil, err
	}

	currentSessionID := resolveCurrentRefreshSessionID(ctx)
	return mapAdminSessions(sessions, currentSessionID), nil
}

// NewsletterSubscribers is the resolver for the newsletterSubscribers field.
func (r *adminQueryResolver) NewsletterSubscribers(
	ctx context.Context,
	filter *model.AdminNewsletterSubscriberFilterInput,
) (*model.AdminNewsletterSubscriberListPayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	resolvedFilter := domain.AdminNewsletterSubscriberFilter{}
	if filter != nil {
		if filter.Locale != nil {
			resolvedFilter.Locale = strings.TrimSpace(*filter.Locale)
		}
		if filter.Status != nil {
			resolvedFilter.Status = mapAdminNewsletterStatusInput(*filter.Status)
		}
		if filter.Query != nil {
			resolvedFilter.Query = strings.TrimSpace(*filter.Query)
		}
		if filter.Page != nil {
			resolvedFilter.Page = filter.Page
		}
		if filter.Size != nil {
			resolvedFilter.Size = filter.Size
		}
	}

	payload, err := appservice.ListAdminNewsletterSubscribers(ctx, adminUser, resolvedFilter)
	if err != nil {
		return nil, err
	}

	return mapAdminNewsletterSubscriberListPayload(payload), nil
}

// ErrorMessages is the resolver for the errorMessages field.
func (r *adminQueryResolver) ErrorMessages(
	ctx context.Context,
	filter *model.AdminErrorMessageFilterInput,
) (*model.AdminErrorMessageListPayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	resolvedFilter := domain.AdminErrorMessageFilter{}
	if filter != nil {
		if filter.Locale != nil {
			resolvedFilter.Locale = strings.TrimSpace(*filter.Locale)
		}
		if filter.Code != nil {
			resolvedFilter.Code = strings.TrimSpace(*filter.Code)
		}
		if filter.Query != nil {
			resolvedFilter.Query = strings.TrimSpace(*filter.Query)
		}
		if filter.Page != nil {
			resolvedFilter.Page = filter.Page
		}
		if filter.Size != nil {
			resolvedFilter.Size = filter.Size
		}
	}

	payload, err := appservice.ListAdminErrorMessages(ctx, adminUser, resolvedFilter)
	if err != nil {
		return nil, err
	}

	return mapAdminErrorMessageListPayload(payload), nil
}

// ContentPosts is the resolver for the contentPosts field.
func (r *adminQueryResolver) ContentPosts(
	ctx context.Context,
	filter *model.AdminContentPostFilterInput,
) (*model.AdminContentPostListPayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	resolvedFilter := domain.AdminContentPostFilter{}
	if filter != nil {
		if filter.Locale != nil {
			resolvedFilter.Locale = strings.TrimSpace(*filter.Locale)
		}
		if filter.PreferredLocale != nil {
			resolvedFilter.PreferredLocale = strings.TrimSpace(*filter.PreferredLocale)
		}
		if filter.Source != nil {
			resolvedFilter.Source = strings.TrimSpace(*filter.Source)
		}
		if filter.Query != nil {
			resolvedFilter.Query = strings.TrimSpace(*filter.Query)
		}
		if filter.CategoryID != nil {
			resolvedFilter.CategoryID = strings.TrimSpace(*filter.CategoryID)
		}
		if filter.TopicID != nil {
			resolvedFilter.TopicID = strings.TrimSpace(*filter.TopicID)
		}
		if filter.Page != nil {
			resolvedFilter.Page = filter.Page
		}
		if filter.Size != nil {
			resolvedFilter.Size = filter.Size
		}
	}

	payload, err := appservice.ListAdminContentPosts(ctx, adminUser, resolvedFilter)
	if err != nil {
		return nil, err
	}

	return mapAdminContentPostListPayload(payload), nil
}

// ContentPost is the resolver for the contentPost field.
func (r *adminQueryResolver) ContentPost(
	ctx context.Context,
	input model.AdminContentEntityKeyInput,
) (*model.AdminContentPost, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	record, err := appservice.GetAdminContentPost(
		ctx,
		adminUser,
		strings.TrimSpace(input.Locale),
		strings.TrimSpace(input.ID),
	)
	if err != nil {
		return nil, err
	}

	return mapAdminContentPost(record), nil
}

// ContentTopicsPage is the resolver for the contentTopicsPage field.
func (r *adminQueryResolver) ContentTopicsPage(
	ctx context.Context,
	filter *model.AdminContentTaxonomyFilterInput,
) (*model.AdminContentTopicListPayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	resolvedFilter := domain.AdminContentTaxonomyFilter{}
	if filter != nil {
		if filter.Locale != nil {
			resolvedFilter.Locale = strings.TrimSpace(*filter.Locale)
		}
		if filter.PreferredLocale != nil {
			resolvedFilter.PreferredLocale = strings.TrimSpace(*filter.PreferredLocale)
		}
		if filter.Query != nil {
			resolvedFilter.Query = strings.TrimSpace(*filter.Query)
		}
		if filter.Page != nil {
			resolvedFilter.Page = filter.Page
		}
		if filter.Size != nil {
			resolvedFilter.Size = filter.Size
		}
	}

	payload, err := appservice.ListAdminContentTopicsPage(ctx, adminUser, resolvedFilter)
	if err != nil {
		return nil, err
	}

	return mapAdminContentTopicListPayload(payload), nil
}

// ContentCategoriesPage is the resolver for the contentCategoriesPage field.
func (r *adminQueryResolver) ContentCategoriesPage(
	ctx context.Context,
	filter *model.AdminContentTaxonomyFilterInput,
) (*model.AdminContentCategoryListPayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	resolvedFilter := domain.AdminContentTaxonomyFilter{}
	if filter != nil {
		if filter.Locale != nil {
			resolvedFilter.Locale = strings.TrimSpace(*filter.Locale)
		}
		if filter.PreferredLocale != nil {
			resolvedFilter.PreferredLocale = strings.TrimSpace(*filter.PreferredLocale)
		}
		if filter.Query != nil {
			resolvedFilter.Query = strings.TrimSpace(*filter.Query)
		}
		if filter.Page != nil {
			resolvedFilter.Page = filter.Page
		}
		if filter.Size != nil {
			resolvedFilter.Size = filter.Size
		}
	}

	payload, err := appservice.ListAdminContentCategoriesPage(ctx, adminUser, resolvedFilter)
	if err != nil {
		return nil, err
	}

	return mapAdminContentCategoryListPayload(payload), nil
}

// ContentTopics is the resolver for the contentTopics field.
func (r *adminQueryResolver) ContentTopics(ctx context.Context, locale *string) ([]*model.AdminContentTopic, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	resolvedLocale := ""
	if locale != nil {
		resolvedLocale = strings.TrimSpace(*locale)
	}

	records, err := appservice.ListAdminContentTopics(ctx, adminUser, resolvedLocale)
	if err != nil {
		return nil, err
	}

	return mapAdminContentTopics(records), nil
}

// ContentCategories is the resolver for the contentCategories field.
func (r *adminQueryResolver) ContentCategories(
	ctx context.Context,
	locale *string,
) ([]*model.AdminContentCategory, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	resolvedLocale := ""
	if locale != nil {
		resolvedLocale = strings.TrimSpace(*locale)
	}

	records, err := appservice.ListAdminContentCategories(ctx, adminUser, resolvedLocale)
	if err != nil {
		return nil, err
	}

	return mapAdminContentCategories(records), nil
}

// ErrorMessageAuditLogs is the resolver for the errorMessageAuditLogs field.
func (r *adminQueryResolver) ErrorMessageAuditLogs(
	ctx context.Context,
	limit *int,
) ([]*model.AdminErrorMessageAuditLog, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	resolvedLimit := 0
	if limit != nil {
		resolvedLimit = *limit
	}

	records, err := appservice.ListAdminErrorMessageAuditLogs(ctx, adminUser, resolvedLimit)
	if err != nil {
		return nil, err
	}

	return mapAdminAuditLogs(records), nil
}

// Login is the resolver for the login field.
func (r *adminMutationResolver) Login(ctx context.Context, input model.AdminLoginInput) (*model.AdminAuthPayload, error) {
	rememberMe := input.RememberMe != nil && *input.RememberMe
	payload, err := appservice.LoginAdmin(
		ctx,
		strings.TrimSpace(input.Email),
		input.Password,
		rememberMe,
		resolveAdminSessionMetadata(ctx, getRequest(ctx)),
	)
	if err != nil {
		return nil, err
	}

	responseWriter := getResponseWriter(ctx)
	config := appconfig.ResolveAdminConfig()
	httpauth.SetSessionCookie(
		responseWriter,
		config.AccessCookieName,
		payload.AccessToken,
		config.SecureCookies,
		"/",
	)
	setAdminRefreshCookie(responseWriter, config, payload)

	return &model.AdminAuthPayload{
		Success: payload.Success,
		User:    mapAdminUser(payload.User),
	}, nil
}

// RefreshAdminSession is the resolver for the refreshAdminSession field.
func (r *adminMutationResolver) RefreshAdminSession(ctx context.Context) (*model.AdminAuthPayload, error) {
	request := getRequest(ctx)
	if request == nil {
		return nil, apperrors.Config("missing admin request context", nil)
	}

	config := appconfig.ResolveAdminConfig()
	refreshCookie, err := request.Cookie(config.RefreshCookieName)
	if err != nil {
		return nil, apperrors.Unauthorized("invalid admin session")
	}

	payload, err := appservice.RefreshAdminSession(
		ctx,
		strings.TrimSpace(refreshCookie.Value),
		resolveAdminSessionMetadata(ctx, request),
	)
	if err != nil {
		return nil, err
	}

	responseWriter := getResponseWriter(ctx)
	httpauth.SetSessionCookie(
		responseWriter,
		config.AccessCookieName,
		payload.AccessToken,
		config.SecureCookies,
		"/",
	)
	setAdminRefreshCookie(responseWriter, config, payload)

	return &model.AdminAuthPayload{
		Success: payload.Success,
		User:    mapAdminUser(payload.User),
	}, nil
}

// Logout is the resolver for the logout field.
func (r *adminMutationResolver) Logout(ctx context.Context) (*model.AdminLogoutPayload, error) {
	request := getRequest(ctx)
	responseWriter := getResponseWriter(ctx)
	config := appconfig.ResolveAdminConfig()
	if request != nil {
		if refreshCookie, err := request.Cookie(config.RefreshCookieName); err == nil {
			if err := appservice.LogoutAdmin(ctx, strings.TrimSpace(refreshCookie.Value)); err != nil {
				return nil, err
			}
		}
	}
	clearAdminSessionCookies(responseWriter, config)

	return &model.AdminLogoutPayload{Success: true}, nil
}

// ChangeName is the resolver for the changeName field.
func (r *adminMutationResolver) ChangeName(
	ctx context.Context,
	input model.AdminChangeNameInput,
) (*model.AdminAuthPayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	updatedAdminUser, err := appservice.ChangeAdminName(ctx, adminUser, input.Name)
	if err != nil {
		return nil, err
	}

	return &model.AdminAuthPayload{
		Success: true,
		User:    mapAdminUser(updatedAdminUser),
	}, nil
}

// ChangeAvatar is the resolver for the changeAvatar field.
func (r *adminMutationResolver) ChangeAvatar(
	ctx context.Context,
	input model.AdminChangeAvatarInput,
) (*model.AdminAuthPayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	updatedAdminUser, err := appservice.ChangeAdminAvatar(ctx, adminUser, input.AvatarURL)
	if err != nil {
		return nil, err
	}

	return &model.AdminAuthPayload{
		Success: true,
		User:    mapAdminUser(updatedAdminUser),
	}, nil
}

// ChangeUsername is the resolver for the changeUsername field.
func (r *adminMutationResolver) ChangeUsername(
	ctx context.Context,
	input model.AdminChangeUsernameInput,
) (*model.AdminAuthPayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	updatedAdminUser, err := appservice.ChangeAdminUsername(ctx, adminUser, input.NewUsername)
	if err != nil {
		return nil, err
	}

	return &model.AdminAuthPayload{
		Success: true,
		User:    mapAdminUser(updatedAdminUser),
	}, nil
}

// DeleteAccount is the resolver for the deleteAccount field.
func (r *adminMutationResolver) DeleteAccount(
	ctx context.Context,
	input model.AdminDeleteAccountInput,
) (*model.AdminAccountDeletePayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	if err := appservice.DeleteAdminAccount(ctx, adminUser, input.CurrentPassword); err != nil {
		return nil, err
	}

	responseWriter := getResponseWriter(ctx)
	config := appconfig.ResolveAdminConfig()
	clearAdminSessionCookies(responseWriter, config)

	return &model.AdminAccountDeletePayload{Success: true}, nil
}

// ChangePassword is the resolver for the changePassword field.
func (r *adminMutationResolver) ChangePassword(ctx context.Context, input model.AdminChangePasswordInput) (*model.AdminPasswordChangePayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	if err := appservice.ChangeAdminPassword(
		ctx,
		adminUser,
		input.CurrentPassword,
		input.NewPassword,
		input.ConfirmPassword,
	); err != nil {
		return nil, err
	}

	responseWriter := getResponseWriter(ctx)
	config := appconfig.ResolveAdminConfig()
	clearAdminSessionCookies(responseWriter, config)

	return &model.AdminPasswordChangePayload{Success: true}, nil
}

// RevokeSession is the resolver for the revokeSession field.
func (r *adminMutationResolver) RevokeSession(ctx context.Context, sessionID string) (*model.AdminSessionRevokePayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	revoked, err := appservice.RevokeAdminSession(ctx, adminUser, sessionID)
	if err != nil {
		return nil, err
	}
	if !revoked {
		return nil, apperrors.BadRequest("session not found")
	}

	if strings.TrimSpace(sessionID) == resolveCurrentRefreshSessionID(ctx) {
		clearAdminSessionCookies(getResponseWriter(ctx), appconfig.ResolveAdminConfig())
	}

	return &model.AdminSessionRevokePayload{Success: true}, nil
}

// RevokeAllSessions is the resolver for the revokeAllSessions field.
func (r *adminMutationResolver) RevokeAllSessions(ctx context.Context) (*model.AdminSessionRevokePayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	if err := appservice.RevokeAllAdminSessions(ctx, adminUser); err != nil {
		return nil, err
	}

	clearAdminSessionCookies(getResponseWriter(ctx), appconfig.ResolveAdminConfig())
	return &model.AdminSessionRevokePayload{Success: true}, nil
}

// UpdateNewsletterSubscriberStatus is the resolver for the updateNewsletterSubscriberStatus field.
func (r *adminMutationResolver) UpdateNewsletterSubscriberStatus(
	ctx context.Context,
	input model.AdminUpdateNewsletterSubscriberStatusInput,
) (*model.AdminNewsletterSubscriber, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	updated, err := appservice.UpdateAdminNewsletterSubscriberStatus(
		ctx,
		adminUser,
		input.Email,
		mapAdminNewsletterStatusInput(input.Status),
	)
	if err != nil {
		return nil, err
	}

	return mapAdminNewsletterSubscriber(updated), nil
}

// DeleteNewsletterSubscriber is the resolver for the deleteNewsletterSubscriber field.
func (r *adminMutationResolver) DeleteNewsletterSubscriber(
	ctx context.Context,
	input model.AdminDeleteNewsletterSubscriberInput,
) (*model.AdminDeletePayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	if err := appservice.DeleteAdminNewsletterSubscriber(ctx, adminUser, input.Email); err != nil {
		return nil, err
	}

	return &model.AdminDeletePayload{Success: true}, nil
}

// CreateErrorMessage is the resolver for the createErrorMessage field.
func (r *adminMutationResolver) CreateErrorMessage(
	ctx context.Context,
	input model.AdminCreateErrorMessageInput,
) (*model.AdminErrorMessage, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}
	if input.Key == nil {
		return nil, apperrors.BadRequest("error message key is required")
	}

	saved, err := appservice.CreateAdminErrorMessage(
		ctx,
		adminUser,
		mapAdminErrorMessageKey(*input.Key),
		input.Message,
	)
	if err != nil {
		return nil, err
	}

	return mapAdminErrorMessage(saved), nil
}

// UpdateErrorMessage is the resolver for the updateErrorMessage field.
func (r *adminMutationResolver) UpdateErrorMessage(
	ctx context.Context,
	input model.AdminUpdateErrorMessageInput,
) (*model.AdminErrorMessage, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}
	if input.Key == nil {
		return nil, apperrors.BadRequest("error message key is required")
	}

	updated, err := appservice.UpdateAdminErrorMessage(
		ctx,
		adminUser,
		mapAdminErrorMessageKey(*input.Key),
		input.Message,
	)
	if err != nil {
		return nil, err
	}

	return mapAdminErrorMessage(updated), nil
}

// DeleteErrorMessage is the resolver for the deleteErrorMessage field.
func (r *adminMutationResolver) DeleteErrorMessage(
	ctx context.Context,
	input model.AdminErrorMessageKeyInput,
) (*model.AdminDeletePayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	if err := appservice.DeleteAdminErrorMessage(ctx, adminUser, mapAdminErrorMessageKey(input)); err != nil {
		return nil, err
	}

	return &model.AdminDeletePayload{Success: true}, nil
}

// UpdateContentPostMetadata is the resolver for the updateContentPostMetadata field.
func (r *adminMutationResolver) UpdateContentPostMetadata(
	ctx context.Context,
	input model.AdminUpdateContentPostMetadataInput,
) (*model.AdminContentPost, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	updated, err := appservice.UpdateAdminContentPostMetadata(ctx, adminUser, domain.AdminContentPostMetadataInput{
		Locale:        strings.TrimSpace(input.Locale),
		ID:            strings.TrimSpace(input.ID),
		Title:         toOptionalTrimmedInputString(input.Title),
		Summary:       toOptionalTrimmedInputString(input.Summary),
		Thumbnail:     toOptionalTrimmedInputString(input.Thumbnail),
		PublishedDate: toOptionalTrimmedInputString(input.PublishedDate),
		UpdatedDate:   toOptionalTrimmedInputString(input.UpdatedDate),
		CategoryID:    strings.TrimSpace(stringPointerValue(input.CategoryID)),
		TopicIDs:      mapAdminContentTopicIDs(input.TopicIds),
	})
	if err != nil {
		return nil, err
	}

	return mapAdminContentPost(updated), nil
}

// UpdateContentPostContent is the resolver for the updateContentPostContent field.
func (r *adminMutationResolver) UpdateContentPostContent(
	ctx context.Context,
	input model.AdminUpdateContentPostContentInput,
) (*model.AdminContentPost, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	updated, err := appservice.UpdateAdminContentPostContent(ctx, adminUser, domain.AdminContentPostContentInput{
		Locale:  strings.TrimSpace(input.Locale),
		ID:      strings.TrimSpace(input.ID),
		Content: input.Content,
	})
	if err != nil {
		return nil, err
	}

	return mapAdminContentPost(updated), nil
}

// DeleteContentPost is the resolver for the deleteContentPost field.
func (r *adminMutationResolver) DeleteContentPost(
	ctx context.Context,
	input model.AdminContentEntityKeyInput,
) (*model.AdminDeletePayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	if err := appservice.DeleteAdminContentPost(
		ctx,
		adminUser,
		strings.TrimSpace(input.Locale),
		strings.TrimSpace(input.ID),
	); err != nil {
		return nil, err
	}

	return &model.AdminDeletePayload{Success: true}, nil
}

// CreateContentTopic is the resolver for the createContentTopic field.
func (r *adminMutationResolver) CreateContentTopic(
	ctx context.Context,
	input model.AdminContentTopicInput,
) (*model.AdminContentTopic, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	saved, err := appservice.CreateAdminContentTopic(ctx, adminUser, mapAdminContentTopicInput(input))
	if err != nil {
		return nil, err
	}

	return mapAdminContentTopic(saved), nil
}

// UpdateContentTopic is the resolver for the updateContentTopic field.
func (r *adminMutationResolver) UpdateContentTopic(
	ctx context.Context,
	input model.AdminContentTopicInput,
) (*model.AdminContentTopic, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	saved, err := appservice.UpdateAdminContentTopic(ctx, adminUser, mapAdminContentTopicInput(input))
	if err != nil {
		return nil, err
	}

	return mapAdminContentTopic(saved), nil
}

// DeleteContentTopic is the resolver for the deleteContentTopic field.
func (r *adminMutationResolver) DeleteContentTopic(
	ctx context.Context,
	input model.AdminContentEntityKeyInput,
) (*model.AdminDeletePayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	if err := appservice.DeleteAdminContentTopic(
		ctx,
		adminUser,
		strings.TrimSpace(input.Locale),
		strings.TrimSpace(input.ID),
	); err != nil {
		return nil, err
	}

	return &model.AdminDeletePayload{Success: true}, nil
}

// CreateContentCategory is the resolver for the createContentCategory field.
func (r *adminMutationResolver) CreateContentCategory(
	ctx context.Context,
	input model.AdminContentCategoryInput,
) (*model.AdminContentCategory, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	saved, err := appservice.CreateAdminContentCategory(ctx, adminUser, mapAdminContentCategoryInput(input))
	if err != nil {
		return nil, err
	}

	return mapAdminContentCategory(saved), nil
}

// UpdateContentCategory is the resolver for the updateContentCategory field.
func (r *adminMutationResolver) UpdateContentCategory(
	ctx context.Context,
	input model.AdminContentCategoryInput,
) (*model.AdminContentCategory, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	saved, err := appservice.UpdateAdminContentCategory(ctx, adminUser, mapAdminContentCategoryInput(input))
	if err != nil {
		return nil, err
	}

	return mapAdminContentCategory(saved), nil
}

// DeleteContentCategory is the resolver for the deleteContentCategory field.
func (r *adminMutationResolver) DeleteContentCategory(
	ctx context.Context,
	input model.AdminContentEntityKeyInput,
) (*model.AdminDeletePayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	if err := appservice.DeleteAdminContentCategory(
		ctx,
		adminUser,
		strings.TrimSpace(input.Locale),
		strings.TrimSpace(input.ID),
	); err != nil {
		return nil, err
	}

	return &model.AdminDeletePayload{Success: true}, nil
}

// AdminMutation returns AdminMutationResolver implementation.
func (r *Resolver) AdminMutation() AdminMutationResolver { return &adminMutationResolver{r} }

// AdminQuery returns AdminQueryResolver implementation.
func (r *Resolver) AdminQuery() AdminQueryResolver { return &adminQueryResolver{r} }

type (
	adminMutationResolver struct{ *Resolver }
	adminQueryResolver    struct{ *Resolver }
)

func mapAdminUser(user *domain.AdminUser) *model.AdminUser {
	if user == nil {
		return nil
	}

	return &model.AdminUser{
		ID:        user.ID,
		Name:      toOptionalAdminProfileName(user.Name),
		Username:  toOptionalAdminUsername(user.Username),
		AvatarURL: toOptionalAdminAvatarURL(user.AvatarURL),
		Email:     user.Email,
		Roles:     append([]string{}, user.Roles...),
	}
}

func toOptionalAdminProfileName(value string) *string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return nil
	}

	return &trimmed
}

func toOptionalAdminUsername(value string) *string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return nil
	}

	return &trimmed
}

func toOptionalAdminAvatarURL(value string) *string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return nil
	}

	return &trimmed
}

func mapAdminDashboard(payload *domain.AdminDashboard) *model.AdminDashboard {
	if payload == nil {
		return &model.AdminDashboard{}
	}

	return &model.AdminDashboard{
		TotalPosts:       payload.TotalPosts,
		TotalSubscribers: payload.TotalSubscribers,
		TopViewedPosts:   mapAdminDashboardPosts(payload.TopViewedPosts),
		TopLikedPosts:    mapAdminDashboardPosts(payload.TopLikedPosts),
		ContentHealth:    mapAdminDashboardContentHealth(payload.ContentHealth),
	}
}

func mapAdminDashboardPosts(items []domain.AdminDashboardPostMetric) []*model.AdminDashboardPost {
	mapped := make([]*model.AdminDashboardPost, 0, len(items))
	for _, item := range items {
		mapped = append(mapped, &model.AdminDashboardPost{
			PostID:        item.PostID,
			Title:         item.Title,
			Locale:        item.Locale,
			PublishedDate: item.PublishedDate,
			Hits:          int(item.Hits),
			Likes:         int(item.Likes),
		})
	}

	return mapped
}

func mapAdminDashboardContentHealth(value domain.AdminDashboardContentHealth) *model.AdminDashboardContentHealth {
	return &model.AdminDashboardContentHealth{
		LocalePairCoverage:  value.LocalePairCoverage,
		MissingTranslations: value.MissingTranslations,
		MissingThumbnails:   value.MissingThumbnails,
		LatestUpdatedPosts:  mapAdminDashboardUpdatedPosts(value.LatestUpdatedPosts),
		DominantCategory:    mapAdminDashboardCategory(value.DominantCategory),
	}
}

func mapAdminDashboardUpdatedPosts(items []domain.AdminDashboardUpdatedPost) []*model.AdminDashboardUpdatedPost {
	mapped := make([]*model.AdminDashboardUpdatedPost, 0, len(items))
	for _, item := range items {
		mapped = append(mapped, &model.AdminDashboardUpdatedPost{
			ID:       item.ID,
			Title:    item.Title,
			Date:     item.Date,
			Category: item.Category,
		})
	}

	return mapped
}

func mapAdminDashboardCategory(value *domain.AdminDashboardCategory) *model.AdminDashboardCategory {
	if value == nil {
		return nil
	}

	return &model.AdminDashboardCategory{
		ID:    value.ID,
		Name:  value.Name,
		Count: value.Count,
	}
}

func mapAdminSessions(items []domain.AdminSessionRecord, currentSessionID string) []*model.AdminSession {
	mapped := make([]*model.AdminSession, 0, len(items))
	for _, item := range items {
		mapped = append(mapped, &model.AdminSession{
			ID:             item.ID,
			Device:         resolveAdminDeviceLabel(item.UserAgent),
			IPAddress:      resolveAdminIPAddressLabel(item.RemoteIP),
			CountryCode:    resolveAdminCountryCodeLabel(item.CountryCode),
			LastActivityAt: item.LastSeenAt.UTC(),
			CreatedAt:      item.CreatedAt.UTC(),
			ExpiresAt:      item.ExpiresAt.UTC(),
			Persistent:     item.Persistent,
			Current:        strings.TrimSpace(item.ID) != "" && strings.TrimSpace(item.ID) == strings.TrimSpace(currentSessionID),
		})
	}

	return mapped
}

func mapAdminNewsletterSubscriberListPayload(
	payload *domain.AdminNewsletterSubscriberListResult,
) *model.AdminNewsletterSubscriberListPayload {
	if payload == nil {
		return &model.AdminNewsletterSubscriberListPayload{
			Items: []*model.AdminNewsletterSubscriber{},
			Total: 0,
			Page:  1,
			Size:  20,
		}
	}

	return &model.AdminNewsletterSubscriberListPayload{
		Items: mapAdminNewsletterSubscribers(payload.Items),
		Total: payload.Total,
		Page:  payload.Page,
		Size:  payload.Size,
	}
}

func mapAdminNewsletterSubscribers(items []domain.AdminNewsletterSubscriberRecord) []*model.AdminNewsletterSubscriber {
	mapped := make([]*model.AdminNewsletterSubscriber, 0, len(items))
	for _, item := range items {
		mapped = append(mapped, mapAdminNewsletterSubscriber(&item))
	}

	return mapped
}

func mapAdminNewsletterSubscriber(item *domain.AdminNewsletterSubscriberRecord) *model.AdminNewsletterSubscriber {
	if item == nil {
		return nil
	}

	return &model.AdminNewsletterSubscriber{
		Email:          item.Email,
		Locale:         item.Locale,
		Status:         mapAdminNewsletterStatusOutput(item.Status),
		Tags:           append([]string{}, item.Tags...),
		FormName:       toOptionalAdminString(item.FormName),
		Source:         toOptionalAdminString(item.Source),
		UpdatedAt:      toOptionalAdminTime(item.UpdatedAt),
		CreatedAt:      toOptionalAdminTime(item.CreatedAt),
		ConfirmedAt:    toOptionalAdminTimePointer(item.ConfirmedAt),
		UnsubscribedAt: toOptionalAdminTimePointer(item.UnsubscribedAt),
	}
}

func mapAdminErrorMessageListPayload(payload *domain.AdminErrorMessageListResult) *model.AdminErrorMessageListPayload {
	if payload == nil {
		return &model.AdminErrorMessageListPayload{
			Items: []*model.AdminErrorMessage{},
			Total: 0,
			Page:  1,
			Size:  20,
		}
	}

	return &model.AdminErrorMessageListPayload{
		Items: mapAdminErrorMessages(payload.Items),
		Total: payload.Total,
		Page:  payload.Page,
		Size:  payload.Size,
	}
}

func mapAdminErrorMessages(items []domain.AdminErrorMessageView) []*model.AdminErrorMessage {
	mapped := make([]*model.AdminErrorMessage, 0, len(items))
	for _, item := range items {
		mapped = append(mapped, mapAdminErrorMessage(&item))
	}

	return mapped
}

func mapAdminErrorMessage(item *domain.AdminErrorMessageView) *model.AdminErrorMessage {
	if item == nil {
		return nil
	}

	return &model.AdminErrorMessage{
		Scope:     item.Scope,
		Locale:    item.Locale,
		Code:      item.Code,
		Message:   item.Message,
		UpdatedAt: toOptionalAdminTime(item.UpdatedAt),
	}
}

func mapAdminContentPostListPayload(payload *domain.AdminContentPostListResult) *model.AdminContentPostListPayload {
	if payload == nil {
		return &model.AdminContentPostListPayload{
			Items: []*model.AdminContentPostGroup{},
			Total: 0,
			Page:  1,
			Size:  20,
		}
	}

	return &model.AdminContentPostListPayload{
		Items: mapAdminContentPostGroups(payload.Items),
		Total: payload.Total,
		Page:  payload.Page,
		Size:  payload.Size,
	}
}

func mapAdminContentPostGroups(items []domain.AdminContentPostGroupRecord) []*model.AdminContentPostGroup {
	mapped := make([]*model.AdminContentPostGroup, 0, len(items))
	for _, item := range items {
		copyItem := item
		mapped = append(mapped, mapAdminContentPostGroup(&copyItem))
	}
	return mapped
}

func mapAdminContentPostGroup(item *domain.AdminContentPostGroupRecord) *model.AdminContentPostGroup {
	if item == nil {
		return nil
	}

	return &model.AdminContentPostGroup{
		ID:        item.ID,
		Source:    item.Source,
		Preferred: mapAdminContentPost(&item.Preferred),
		En:        mapAdminContentPost(item.EN),
		Tr:        mapAdminContentPost(item.TR),
	}
}

func mapAdminContentTopicListPayload(
	payload *domain.AdminContentTopicListResult,
) *model.AdminContentTopicListPayload {
	if payload == nil {
		return &model.AdminContentTopicListPayload{
			Items: []*model.AdminContentTopicGroup{},
			Total: 0,
			Page:  1,
			Size:  20,
		}
	}

	return &model.AdminContentTopicListPayload{
		Items: mapAdminContentTopicGroups(payload.Items),
		Total: payload.Total,
		Page:  payload.Page,
		Size:  payload.Size,
	}
}

func mapAdminContentCategoryListPayload(
	payload *domain.AdminContentCategoryListResult,
) *model.AdminContentCategoryListPayload {
	if payload == nil {
		return &model.AdminContentCategoryListPayload{
			Items: []*model.AdminContentCategoryGroup{},
			Total: 0,
			Page:  1,
			Size:  20,
		}
	}

	return &model.AdminContentCategoryListPayload{
		Items: mapAdminContentCategoryGroups(payload.Items),
		Total: payload.Total,
		Page:  payload.Page,
		Size:  payload.Size,
	}
}

func mapAdminContentTopicGroups(items []domain.AdminContentTopicGroupRecord) []*model.AdminContentTopicGroup {
	mapped := make([]*model.AdminContentTopicGroup, 0, len(items))
	for _, item := range items {
		copyItem := item
		mapped = append(mapped, mapAdminContentTopicGroup(&copyItem))
	}
	return mapped
}

func mapAdminContentTopicGroup(item *domain.AdminContentTopicGroupRecord) *model.AdminContentTopicGroup {
	if item == nil {
		return nil
	}

	return &model.AdminContentTopicGroup{
		ID:        item.ID,
		Preferred: mapAdminContentTopic(&item.Preferred),
		En:        mapAdminContentTopic(item.EN),
		Tr:        mapAdminContentTopic(item.TR),
	}
}

func mapAdminContentCategoryGroups(items []domain.AdminContentCategoryGroupRecord) []*model.AdminContentCategoryGroup {
	mapped := make([]*model.AdminContentCategoryGroup, 0, len(items))
	for _, item := range items {
		copyItem := item
		mapped = append(mapped, mapAdminContentCategoryGroup(&copyItem))
	}
	return mapped
}

func mapAdminContentCategoryGroup(item *domain.AdminContentCategoryGroupRecord) *model.AdminContentCategoryGroup {
	if item == nil {
		return nil
	}

	return &model.AdminContentCategoryGroup{
		ID:        item.ID,
		Preferred: mapAdminContentCategory(&item.Preferred),
		En:        mapAdminContentCategory(item.EN),
		Tr:        mapAdminContentCategory(item.TR),
	}
}

func mapAdminContentPost(item *domain.AdminContentPostRecord) *model.AdminContentPost {
	if item == nil {
		return nil
	}

	return &model.AdminContentPost{
		Locale:           item.Locale,
		ID:               item.ID,
		Title:            item.Title,
		Summary:          toOptionalAdminString(item.Summary),
		Content:          toOptionalAdminString(item.Content),
		ContentMode:      toOptionalAdminString(item.ContentMode),
		Thumbnail:        toOptionalAdminString(item.Thumbnail),
		Source:           item.Source,
		PublishedDate:    item.PublishedDate,
		UpdatedDate:      toOptionalAdminString(item.UpdatedDate),
		CategoryID:       toOptionalAdminString(item.CategoryID),
		CategoryName:     toOptionalAdminString(item.CategoryName),
		TopicIds:         append([]string{}, item.TopicIDs...),
		TopicNames:       append([]string{}, item.TopicNames...),
		ContentUpdatedAt: toOptionalAdminTime(item.ContentUpdatedAt),
		UpdatedAt:        toOptionalAdminTime(item.UpdatedAt),
	}
}

func mapAdminContentTopics(items []domain.AdminContentTopicRecord) []*model.AdminContentTopic {
	mapped := make([]*model.AdminContentTopic, 0, len(items))
	for _, item := range items {
		copyItem := item
		mapped = append(mapped, mapAdminContentTopic(&copyItem))
	}
	return mapped
}

func mapAdminContentTopic(item *domain.AdminContentTopicRecord) *model.AdminContentTopic {
	if item == nil {
		return nil
	}

	return &model.AdminContentTopic{
		Locale:    item.Locale,
		ID:        item.ID,
		Name:      item.Name,
		Color:     item.Color,
		Link:      toOptionalAdminString(item.Link),
		UpdatedAt: toOptionalAdminTime(item.UpdatedAt),
	}
}

func mapAdminContentCategories(items []domain.AdminContentCategoryRecord) []*model.AdminContentCategory {
	mapped := make([]*model.AdminContentCategory, 0, len(items))
	for _, item := range items {
		copyItem := item
		mapped = append(mapped, mapAdminContentCategory(&copyItem))
	}
	return mapped
}

func mapAdminContentCategory(item *domain.AdminContentCategoryRecord) *model.AdminContentCategory {
	if item == nil {
		return nil
	}

	return &model.AdminContentCategory{
		Locale:    item.Locale,
		ID:        item.ID,
		Name:      item.Name,
		Color:     item.Color,
		Icon:      toOptionalAdminString(item.Icon),
		Link:      toOptionalAdminString(item.Link),
		UpdatedAt: toOptionalAdminTime(item.UpdatedAt),
	}
}

func mapAdminAuditLogs(items []domain.AdminAuditLogRecord) []*model.AdminErrorMessageAuditLog {
	mapped := make([]*model.AdminErrorMessageAuditLog, 0, len(items))
	for _, item := range items {
		createdAt := item.CreatedAt.UTC()
		if createdAt.IsZero() {
			createdAt = time.Now().UTC()
		}

		mapped = append(mapped, &model.AdminErrorMessageAuditLog{
			ID:          item.ID,
			ActorID:     item.ActorID,
			ActorEmail:  item.ActorEmail,
			Action:      item.Action,
			Scope:       item.Scope,
			Locale:      item.Locale,
			Code:        item.Code,
			BeforeValue: item.BeforeValue,
			AfterValue:  item.AfterValue,
			Status:      item.Status,
			FailureCode: toOptionalAdminString(item.FailureCode),
			RequestID:   toOptionalAdminString(item.RequestID),
			RemoteIP:    toOptionalAdminString(item.RemoteIP),
			CountryCode: toOptionalAdminString(item.CountryCode),
			UserAgent:   toOptionalAdminString(item.UserAgent),
			CreatedAt:   createdAt,
		})
	}

	return mapped
}

func mapAdminErrorMessageKey(input model.AdminErrorMessageKeyInput) domain.AdminErrorMessageKey {
	scope := ""
	if input.Scope != nil {
		scope = strings.TrimSpace(*input.Scope)
	}

	return domain.AdminErrorMessageKey{
		Scope:  scope,
		Locale: strings.TrimSpace(input.Locale),
		Code:   strings.TrimSpace(input.Code),
	}
}

func mapAdminContentTopicInput(input model.AdminContentTopicInput) domain.AdminContentTopicInput {
	return domain.AdminContentTopicInput{
		Locale: strings.TrimSpace(input.Locale),
		ID:     strings.TrimSpace(input.ID),
		Name:   strings.TrimSpace(input.Name),
		Color:  strings.TrimSpace(input.Color),
		Link:   strings.TrimSpace(stringPointerValue(input.Link)),
	}
}

func mapAdminContentCategoryInput(input model.AdminContentCategoryInput) domain.AdminContentCategoryInput {
	return domain.AdminContentCategoryInput{
		Locale: strings.TrimSpace(input.Locale),
		ID:     strings.TrimSpace(input.ID),
		Name:   strings.TrimSpace(input.Name),
		Color:  strings.TrimSpace(input.Color),
		Icon:   strings.TrimSpace(stringPointerValue(input.Icon)),
		Link:   strings.TrimSpace(stringPointerValue(input.Link)),
	}
}

func mapAdminContentTopicIDs(values []string) []string {
	if len(values) == 0 {
		return []string{}
	}

	ids := make([]string, 0, len(values))
	for _, value := range values {
		trimmed := strings.TrimSpace(value)
		if trimmed == "" {
			continue
		}
		ids = append(ids, trimmed)
	}

	return ids
}

func stringPointerValue(value *string) string {
	if value == nil {
		return ""
	}
	return *value
}

func toOptionalTrimmedInputString(value *string) *string {
	if value == nil {
		return nil
	}
	trimmed := strings.TrimSpace(*value)
	return &trimmed
}

func toOptionalAdminString(value string) *string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return nil
	}

	return &trimmed
}

func toOptionalAdminTime(value time.Time) *time.Time {
	if value.IsZero() {
		return nil
	}

	normalized := value.UTC()
	return &normalized
}

func toOptionalAdminTimePointer(value *time.Time) *time.Time {
	if value == nil {
		return nil
	}
	return toOptionalAdminTime(*value)
}

func mapAdminNewsletterStatusInput(value model.AdminNewsletterSubscriberStatus) string {
	switch value {
	case model.AdminNewsletterSubscriberStatusActive:
		return "active"
	case model.AdminNewsletterSubscriberStatusUnsubscribed:
		return "unsubscribed"
	default:
		return "pending"
	}
}

func mapAdminNewsletterStatusOutput(value string) model.AdminNewsletterSubscriberStatus {
	switch strings.TrimSpace(strings.ToLower(value)) {
	case "active":
		return model.AdminNewsletterSubscriberStatusActive
	case "unsubscribed":
		return model.AdminNewsletterSubscriberStatusUnsubscribed
	default:
		return model.AdminNewsletterSubscriberStatusPending
	}
}

func resolveAdminDeviceLabel(userAgent string) string {
	normalized := strings.ToLower(strings.TrimSpace(userAgent))
	if normalized == "" {
		return "Unknown device"
	}

	browser := resolveBrowserLabel(normalized)
	os := resolveOSLabel(normalized)
	switch {
	case browser != "" && os != "":
		return browser + " on " + os
	case browser != "":
		return browser
	case os != "":
		return os
	case strings.Contains(normalized, "iphone"),
		strings.Contains(normalized, "android"),
		strings.Contains(normalized, "mobile"):
		return "Mobile browser"
	case strings.Contains(normalized, "ipad"),
		strings.Contains(normalized, "tablet"):
		return "Tablet browser"
	case strings.Contains(normalized, "macintosh"),
		strings.Contains(normalized, "windows"),
		strings.Contains(normalized, "linux"),
		strings.Contains(normalized, "x11"):
		return "Desktop browser"
	default:
		return "Browser"
	}
}

func resolveBrowserLabel(userAgent string) string {
	switch {
	case strings.Contains(userAgent, "edg/"):
		return "Edge"
	case strings.Contains(userAgent, "opr/"), strings.Contains(userAgent, "opera/"):
		return "Opera"
	case strings.Contains(userAgent, "firefox/"):
		return "Firefox"
	case strings.Contains(userAgent, "chrome/"):
		return "Chrome"
	case strings.Contains(userAgent, "safari/"), strings.Contains(userAgent, "version/"):
		return "Safari"
	case strings.Contains(userAgent, "chromium/"):
		return "Chromium"
	default:
		return ""
	}
}

func resolveOSLabel(userAgent string) string {
	switch {
	case strings.Contains(userAgent, "iphone"), strings.Contains(userAgent, "ipad"), strings.Contains(userAgent, "ios"):
		return "iOS"
	case strings.Contains(userAgent, "android"):
		return "Android"
	case strings.Contains(userAgent, "mac os x"), strings.Contains(userAgent, "macintosh"):
		return "macOS"
	case strings.Contains(userAgent, "windows nt"):
		return "Windows"
	case strings.Contains(userAgent, "cros"):
		return "ChromeOS"
	case strings.Contains(userAgent, "linux"), strings.Contains(userAgent, "x11"):
		return "Linux"
	default:
		return ""
	}
}

func resolveAdminIPAddressLabel(ipAddress string) string {
	trimmed := strings.TrimSpace(ipAddress)
	if trimmed == "" {
		return "Unknown"
	}

	return trimmed
}

func resolveAdminCountryCodeLabel(countryCode string) string {
	trimmed := strings.TrimSpace(strings.ToUpper(countryCode))
	if len(trimmed) != 2 {
		return "Unknown"
	}

	return trimmed
}

func resolveCurrentRefreshSessionID(ctx context.Context) string {
	request := getRequest(ctx)
	if request == nil {
		return ""
	}

	config := appconfig.ResolveAdminConfig()
	if strings.TrimSpace(config.JWTSecret) == "" {
		return ""
	}

	refreshCookie, err := request.Cookie(config.RefreshCookieName)
	if err != nil {
		return ""
	}

	claims, err := httpauth.VerifyHS256JWT(strings.TrimSpace(refreshCookie.Value), config.JWTSecret, "refresh", time.Now().UTC())
	if err != nil {
		return ""
	}

	return strings.TrimSpace(claims.ID)
}

func resolveAdminSessionMetadata(ctx context.Context, request *http.Request) appservice.AdminSessionMetadata {
	metadata := appservice.AdminSessionMetadata{}
	if trace, ok := httpapi.RequestTraceFromContext(ctx); ok {
		metadata.RemoteIP = strings.TrimSpace(trace.RemoteIP)
		metadata.UserAgent = strings.TrimSpace(trace.UserAgent)
		metadata.CountryCode = strings.TrimSpace(strings.ToUpper(trace.CountryCode))
	}

	if request != nil && strings.TrimSpace(metadata.UserAgent) == "" {
		metadata.UserAgent = strings.TrimSpace(request.UserAgent())
	}
	if request != nil && strings.TrimSpace(metadata.CountryCode) == "" {
		metadata.CountryCode = resolveCountryCodeFromRequest(request)
	}

	return metadata
}

func resolveCountryCodeFromRequest(request *http.Request) string {
	if request == nil {
		return ""
	}

	for _, header := range []string{"CF-IPCountry", "X-Country-Code", "X-AppEngine-Country"} {
		value := strings.TrimSpace(strings.ToUpper(request.Header.Get(header)))
		if len(value) == 2 {
			return value
		}
	}

	return ""
}

func clearAdminSessionCookies(responseWriter http.ResponseWriter, config appconfig.AdminConfig) {
	httpauth.ClearCookie(responseWriter, config.AccessCookieName, config.SecureCookies, "/")
	httpauth.ClearCookie(responseWriter, config.RefreshCookieName, config.SecureCookies, "/api/admin")
	httpauth.ClearClientCookie(responseWriter, config.CSRFCookieName, config.SecureCookies, "/")
}

func setAdminRefreshCookie(
	responseWriter http.ResponseWriter,
	config appconfig.AdminConfig,
	payload *appservice.AdminAuthResponse,
) {
	if payload == nil {
		return
	}

	if payload.RememberMe {
		httpauth.SetCookie(
			responseWriter,
			config.RefreshCookieName,
			payload.RefreshToken,
			int(payload.RefreshTTL.Seconds()),
			config.SecureCookies,
			"/api/admin",
		)
		return
	}

	httpauth.SetSessionCookie(
		responseWriter,
		config.RefreshCookieName,
		payload.RefreshToken,
		config.SecureCookies,
		"/api/admin",
	)
}
