package admingraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"net/http"
	"strings"

	appconfig "suaybsimsek.com/blog-api/internal/config"
	"suaybsimsek.com/blog-api/internal/domain"
	"suaybsimsek.com/blog-api/internal/graphql/admin/model"
	appservice "suaybsimsek.com/blog-api/internal/service"
	"suaybsimsek.com/blog-api/pkg/apperrors"
	"suaybsimsek.com/blog-api/pkg/httpauth"
)

// Me is the resolver for the me field.
func (r *adminQueryResolver) Me(ctx context.Context) (*model.AdminMe, error) {
	user := getAdminUser(ctx)
	if user == nil {
		return &model.AdminMe{Authenticated: false}, nil
	}

	return &model.AdminMe{
		Authenticated: true,
		User:          mapAdminUser(user),
	}, nil
}

// Dashboard is the resolver for the dashboard field.
func (r *adminQueryResolver) Dashboard(ctx context.Context) (*model.AdminDashboard, error) {
	if _, err := requireAdminUser(ctx); err != nil {
		return nil, err
	}

	payload, err := appservice.QueryAdminDashboard(ctx)
	if err != nil {
		return nil, err
	}

	return mapAdminDashboard(payload), nil
}

// Login is the resolver for the login field.
func (r *adminMutationResolver) Login(ctx context.Context, input model.AdminLoginInput) (*model.AdminAuthPayload, error) {
	rememberMe := input.RememberMe != nil && *input.RememberMe
	payload, err := appservice.LoginAdmin(ctx, strings.TrimSpace(input.Email), input.Password, rememberMe)
	if err != nil {
		return nil, err
	}

	responseWriter := getResponseWriter(ctx)
	config := appconfig.ResolveAdminConfig()
	httpauth.SetSessionCookie(
		responseWriter,
		config.AccessCookieName,
		payload.AccessToken,
		config.SecureCookies,
		"/",
	)
	setAdminRefreshCookie(responseWriter, config, payload)

	return &model.AdminAuthPayload{
		Success: payload.Success,
		User:    mapAdminUser(payload.User),
	}, nil
}

// RefreshAdminSession is the resolver for the refreshAdminSession field.
func (r *adminMutationResolver) RefreshAdminSession(ctx context.Context) (*model.AdminAuthPayload, error) {
	request := getRequest(ctx)
	if request == nil {
		return nil, apperrors.Config("missing admin request context", nil)
	}

	config := appconfig.ResolveAdminConfig()
	refreshCookie, err := request.Cookie(config.RefreshCookieName)
	if err != nil {
		return nil, apperrors.Unauthorized("invalid admin session")
	}

	payload, err := appservice.RefreshAdminSession(ctx, strings.TrimSpace(refreshCookie.Value))
	if err != nil {
		return nil, err
	}

	responseWriter := getResponseWriter(ctx)
	httpauth.SetSessionCookie(
		responseWriter,
		config.AccessCookieName,
		payload.AccessToken,
		config.SecureCookies,
		"/",
	)
	setAdminRefreshCookie(responseWriter, config, payload)

	return &model.AdminAuthPayload{
		Success: payload.Success,
		User:    mapAdminUser(payload.User),
	}, nil
}

// Logout is the resolver for the logout field.
func (r *adminMutationResolver) Logout(ctx context.Context) (*model.AdminLogoutPayload, error) {
	request := getRequest(ctx)
	responseWriter := getResponseWriter(ctx)
	config := appconfig.ResolveAdminConfig()
	if request != nil {
		if refreshCookie, err := request.Cookie(config.RefreshCookieName); err == nil {
			if err := appservice.LogoutAdmin(ctx, strings.TrimSpace(refreshCookie.Value)); err != nil {
				return nil, err
			}
		}
	}
	httpauth.ClearCookie(responseWriter, config.AccessCookieName, config.SecureCookies, "/")
	httpauth.ClearCookie(responseWriter, config.RefreshCookieName, config.SecureCookies, "/api/admin")
	httpauth.ClearClientCookie(responseWriter, config.CSRFCookieName, config.SecureCookies, "/")

	return &model.AdminLogoutPayload{Success: true}, nil
}

// ChangePassword is the resolver for the changePassword field.
func (r *adminMutationResolver) ChangePassword(ctx context.Context, input model.AdminChangePasswordInput) (*model.AdminPasswordChangePayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	if err := appservice.ChangeAdminPassword(
		ctx,
		adminUser,
		input.CurrentPassword,
		input.NewPassword,
		input.ConfirmPassword,
	); err != nil {
		return nil, err
	}

	responseWriter := getResponseWriter(ctx)
	config := appconfig.ResolveAdminConfig()
	httpauth.ClearCookie(responseWriter, config.AccessCookieName, config.SecureCookies, "/")
	httpauth.ClearCookie(responseWriter, config.RefreshCookieName, config.SecureCookies, "/api/admin")
	httpauth.ClearClientCookie(responseWriter, config.CSRFCookieName, config.SecureCookies, "/")

	return &model.AdminPasswordChangePayload{Success: true}, nil
}

// AdminMutation returns AdminMutationResolver implementation.
func (r *Resolver) AdminMutation() AdminMutationResolver { return &adminMutationResolver{r} }

// AdminQuery returns AdminQueryResolver implementation.
func (r *Resolver) AdminQuery() AdminQueryResolver { return &adminQueryResolver{r} }

type (
	adminMutationResolver struct{ *Resolver }
	adminQueryResolver    struct{ *Resolver }
)

func mapAdminUser(user *domain.AdminUser) *model.AdminUser {
	if user == nil {
		return nil
	}

	return &model.AdminUser{
		ID:       user.ID,
		Username: toOptionalAdminUsername(user.Username),
		Email:    user.Email,
		Roles:    append([]string{}, user.Roles...),
	}
}

func toOptionalAdminUsername(value string) *string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return nil
	}

	return &trimmed
}

func mapAdminDashboard(payload *domain.AdminDashboard) *model.AdminDashboard {
	if payload == nil {
		return &model.AdminDashboard{}
	}

	return &model.AdminDashboard{
		TotalPosts:       payload.TotalPosts,
		TotalSubscribers: payload.TotalSubscribers,
		TopViewedPosts:   mapAdminDashboardPosts(payload.TopViewedPosts),
		TopLikedPosts:    mapAdminDashboardPosts(payload.TopLikedPosts),
		ContentHealth:    mapAdminDashboardContentHealth(payload.ContentHealth),
	}
}

func mapAdminDashboardPosts(items []domain.AdminDashboardPostMetric) []*model.AdminDashboardPost {
	mapped := make([]*model.AdminDashboardPost, 0, len(items))
	for _, item := range items {
		mapped = append(mapped, &model.AdminDashboardPost{
			PostID:        item.PostID,
			Title:         item.Title,
			Locale:        item.Locale,
			PublishedDate: item.PublishedDate,
			Hits:          int(item.Hits),
			Likes:         int(item.Likes),
		})
	}

	return mapped
}

func mapAdminDashboardContentHealth(value domain.AdminDashboardContentHealth) *model.AdminDashboardContentHealth {
	return &model.AdminDashboardContentHealth{
		LocalePairCoverage:  value.LocalePairCoverage,
		MissingTranslations: value.MissingTranslations,
		MissingThumbnails:   value.MissingThumbnails,
		LatestUpdatedPosts:  mapAdminDashboardUpdatedPosts(value.LatestUpdatedPosts),
		DominantCategory:    mapAdminDashboardCategory(value.DominantCategory),
	}
}

func mapAdminDashboardUpdatedPosts(items []domain.AdminDashboardUpdatedPost) []*model.AdminDashboardUpdatedPost {
	mapped := make([]*model.AdminDashboardUpdatedPost, 0, len(items))
	for _, item := range items {
		mapped = append(mapped, &model.AdminDashboardUpdatedPost{
			ID:       item.ID,
			Title:    item.Title,
			Date:     item.Date,
			Category: item.Category,
		})
	}

	return mapped
}

func mapAdminDashboardCategory(value *domain.AdminDashboardCategory) *model.AdminDashboardCategory {
	if value == nil {
		return nil
	}

	return &model.AdminDashboardCategory{
		ID:    value.ID,
		Name:  value.Name,
		Count: value.Count,
	}
}

func setAdminRefreshCookie(
	responseWriter http.ResponseWriter,
	config appconfig.AdminConfig,
	payload *appservice.AdminAuthResponse,
) {
	if payload == nil {
		return
	}

	if payload.RememberMe {
		httpauth.SetCookie(
			responseWriter,
			config.RefreshCookieName,
			payload.RefreshToken,
			int(payload.RefreshTTL.Seconds()),
			config.SecureCookies,
			"/api/admin",
		)
		return
	}

	httpauth.SetSessionCookie(
		responseWriter,
		config.RefreshCookieName,
		payload.RefreshToken,
		config.SecureCookies,
		"/api/admin",
	)
}
