package admingraphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"net/http"
	"strings"
	"time"

	appconfig "suaybsimsek.com/blog-api/internal/config"
	"suaybsimsek.com/blog-api/internal/domain"
	"suaybsimsek.com/blog-api/internal/graphql/admin/model"
	appservice "suaybsimsek.com/blog-api/internal/service"
	"suaybsimsek.com/blog-api/pkg/apperrors"
	"suaybsimsek.com/blog-api/pkg/httpapi"
	"suaybsimsek.com/blog-api/pkg/httpauth"
)

// Me is the resolver for the me field.
func (r *adminQueryResolver) Me(ctx context.Context) (*model.AdminMe, error) {
	user := getAdminUser(ctx)
	if user == nil {
		return &model.AdminMe{Authenticated: false}, nil
	}

	return &model.AdminMe{
		Authenticated: true,
		User:          mapAdminUser(user),
	}, nil
}

// Dashboard is the resolver for the dashboard field.
func (r *adminQueryResolver) Dashboard(ctx context.Context) (*model.AdminDashboard, error) {
	if _, err := requireAdminUser(ctx); err != nil {
		return nil, err
	}

	payload, err := appservice.QueryAdminDashboard(ctx)
	if err != nil {
		return nil, err
	}

	return mapAdminDashboard(payload), nil
}

// ActiveSessions is the resolver for the activeSessions field.
func (r *adminQueryResolver) ActiveSessions(ctx context.Context) ([]*model.AdminSession, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	sessions, err := appservice.ListActiveAdminSessions(ctx, adminUser)
	if err != nil {
		return nil, err
	}

	currentSessionID := resolveCurrentRefreshSessionID(ctx)
	return mapAdminSessions(sessions, currentSessionID), nil
}

// Login is the resolver for the login field.
func (r *adminMutationResolver) Login(ctx context.Context, input model.AdminLoginInput) (*model.AdminAuthPayload, error) {
	rememberMe := input.RememberMe != nil && *input.RememberMe
	payload, err := appservice.LoginAdmin(
		ctx,
		strings.TrimSpace(input.Email),
		input.Password,
		rememberMe,
		resolveAdminSessionMetadata(ctx, getRequest(ctx)),
	)
	if err != nil {
		return nil, err
	}

	responseWriter := getResponseWriter(ctx)
	config := appconfig.ResolveAdminConfig()
	httpauth.SetSessionCookie(
		responseWriter,
		config.AccessCookieName,
		payload.AccessToken,
		config.SecureCookies,
		"/",
	)
	setAdminRefreshCookie(responseWriter, config, payload)

	return &model.AdminAuthPayload{
		Success: payload.Success,
		User:    mapAdminUser(payload.User),
	}, nil
}

// RefreshAdminSession is the resolver for the refreshAdminSession field.
func (r *adminMutationResolver) RefreshAdminSession(ctx context.Context) (*model.AdminAuthPayload, error) {
	request := getRequest(ctx)
	if request == nil {
		return nil, apperrors.Config("missing admin request context", nil)
	}

	config := appconfig.ResolveAdminConfig()
	refreshCookie, err := request.Cookie(config.RefreshCookieName)
	if err != nil {
		return nil, apperrors.Unauthorized("invalid admin session")
	}

	payload, err := appservice.RefreshAdminSession(
		ctx,
		strings.TrimSpace(refreshCookie.Value),
		resolveAdminSessionMetadata(ctx, request),
	)
	if err != nil {
		return nil, err
	}

	responseWriter := getResponseWriter(ctx)
	httpauth.SetSessionCookie(
		responseWriter,
		config.AccessCookieName,
		payload.AccessToken,
		config.SecureCookies,
		"/",
	)
	setAdminRefreshCookie(responseWriter, config, payload)

	return &model.AdminAuthPayload{
		Success: payload.Success,
		User:    mapAdminUser(payload.User),
	}, nil
}

// Logout is the resolver for the logout field.
func (r *adminMutationResolver) Logout(ctx context.Context) (*model.AdminLogoutPayload, error) {
	request := getRequest(ctx)
	responseWriter := getResponseWriter(ctx)
	config := appconfig.ResolveAdminConfig()
	if request != nil {
		if refreshCookie, err := request.Cookie(config.RefreshCookieName); err == nil {
			if err := appservice.LogoutAdmin(ctx, strings.TrimSpace(refreshCookie.Value)); err != nil {
				return nil, err
			}
		}
	}
	clearAdminSessionCookies(responseWriter, config)

	return &model.AdminLogoutPayload{Success: true}, nil
}

// ChangeName is the resolver for the changeName field.
func (r *adminMutationResolver) ChangeName(
	ctx context.Context,
	input model.AdminChangeNameInput,
) (*model.AdminAuthPayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	updatedAdminUser, err := appservice.ChangeAdminName(ctx, adminUser, input.Name)
	if err != nil {
		return nil, err
	}

	return &model.AdminAuthPayload{
		Success: true,
		User:    mapAdminUser(updatedAdminUser),
	}, nil
}

// ChangeAvatar is the resolver for the changeAvatar field.
func (r *adminMutationResolver) ChangeAvatar(
	ctx context.Context,
	input model.AdminChangeAvatarInput,
) (*model.AdminAuthPayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	updatedAdminUser, err := appservice.ChangeAdminAvatar(ctx, adminUser, input.AvatarURL)
	if err != nil {
		return nil, err
	}

	return &model.AdminAuthPayload{
		Success: true,
		User:    mapAdminUser(updatedAdminUser),
	}, nil
}

// ChangeUsername is the resolver for the changeUsername field.
func (r *adminMutationResolver) ChangeUsername(
	ctx context.Context,
	input model.AdminChangeUsernameInput,
) (*model.AdminAuthPayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	updatedAdminUser, err := appservice.ChangeAdminUsername(ctx, adminUser, input.NewUsername)
	if err != nil {
		return nil, err
	}

	return &model.AdminAuthPayload{
		Success: true,
		User:    mapAdminUser(updatedAdminUser),
	}, nil
}

// DeleteAccount is the resolver for the deleteAccount field.
func (r *adminMutationResolver) DeleteAccount(
	ctx context.Context,
	input model.AdminDeleteAccountInput,
) (*model.AdminAccountDeletePayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	if err := appservice.DeleteAdminAccount(ctx, adminUser, input.CurrentPassword); err != nil {
		return nil, err
	}

	responseWriter := getResponseWriter(ctx)
	config := appconfig.ResolveAdminConfig()
	clearAdminSessionCookies(responseWriter, config)

	return &model.AdminAccountDeletePayload{Success: true}, nil
}

// ChangePassword is the resolver for the changePassword field.
func (r *adminMutationResolver) ChangePassword(ctx context.Context, input model.AdminChangePasswordInput) (*model.AdminPasswordChangePayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	if err := appservice.ChangeAdminPassword(
		ctx,
		adminUser,
		input.CurrentPassword,
		input.NewPassword,
		input.ConfirmPassword,
	); err != nil {
		return nil, err
	}

	responseWriter := getResponseWriter(ctx)
	config := appconfig.ResolveAdminConfig()
	clearAdminSessionCookies(responseWriter, config)

	return &model.AdminPasswordChangePayload{Success: true}, nil
}

// RevokeSession is the resolver for the revokeSession field.
func (r *adminMutationResolver) RevokeSession(ctx context.Context, sessionID string) (*model.AdminSessionRevokePayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	revoked, err := appservice.RevokeAdminSession(ctx, adminUser, sessionID)
	if err != nil {
		return nil, err
	}
	if !revoked {
		return nil, apperrors.BadRequest("session not found")
	}

	if strings.TrimSpace(sessionID) == resolveCurrentRefreshSessionID(ctx) {
		clearAdminSessionCookies(getResponseWriter(ctx), appconfig.ResolveAdminConfig())
	}

	return &model.AdminSessionRevokePayload{Success: true}, nil
}

// RevokeAllSessions is the resolver for the revokeAllSessions field.
func (r *adminMutationResolver) RevokeAllSessions(ctx context.Context) (*model.AdminSessionRevokePayload, error) {
	adminUser, err := requireAdminUser(ctx)
	if err != nil {
		return nil, err
	}

	if err := appservice.RevokeAllAdminSessions(ctx, adminUser); err != nil {
		return nil, err
	}

	clearAdminSessionCookies(getResponseWriter(ctx), appconfig.ResolveAdminConfig())
	return &model.AdminSessionRevokePayload{Success: true}, nil
}

// AdminMutation returns AdminMutationResolver implementation.
func (r *Resolver) AdminMutation() AdminMutationResolver { return &adminMutationResolver{r} }

// AdminQuery returns AdminQueryResolver implementation.
func (r *Resolver) AdminQuery() AdminQueryResolver { return &adminQueryResolver{r} }

type (
	adminMutationResolver struct{ *Resolver }
	adminQueryResolver    struct{ *Resolver }
)

func mapAdminUser(user *domain.AdminUser) *model.AdminUser {
	if user == nil {
		return nil
	}

	return &model.AdminUser{
		ID:        user.ID,
		Name:      toOptionalAdminProfileName(user.Name),
		Username:  toOptionalAdminUsername(user.Username),
		AvatarURL: toOptionalAdminAvatarURL(user.AvatarURL),
		Email:     user.Email,
		Roles:     append([]string{}, user.Roles...),
	}
}

func toOptionalAdminProfileName(value string) *string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return nil
	}

	return &trimmed
}

func toOptionalAdminUsername(value string) *string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return nil
	}

	return &trimmed
}

func toOptionalAdminAvatarURL(value string) *string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return nil
	}

	return &trimmed
}

func mapAdminDashboard(payload *domain.AdminDashboard) *model.AdminDashboard {
	if payload == nil {
		return &model.AdminDashboard{}
	}

	return &model.AdminDashboard{
		TotalPosts:       payload.TotalPosts,
		TotalSubscribers: payload.TotalSubscribers,
		TopViewedPosts:   mapAdminDashboardPosts(payload.TopViewedPosts),
		TopLikedPosts:    mapAdminDashboardPosts(payload.TopLikedPosts),
		ContentHealth:    mapAdminDashboardContentHealth(payload.ContentHealth),
	}
}

func mapAdminDashboardPosts(items []domain.AdminDashboardPostMetric) []*model.AdminDashboardPost {
	mapped := make([]*model.AdminDashboardPost, 0, len(items))
	for _, item := range items {
		mapped = append(mapped, &model.AdminDashboardPost{
			PostID:        item.PostID,
			Title:         item.Title,
			Locale:        item.Locale,
			PublishedDate: item.PublishedDate,
			Hits:          int(item.Hits),
			Likes:         int(item.Likes),
		})
	}

	return mapped
}

func mapAdminDashboardContentHealth(value domain.AdminDashboardContentHealth) *model.AdminDashboardContentHealth {
	return &model.AdminDashboardContentHealth{
		LocalePairCoverage:  value.LocalePairCoverage,
		MissingTranslations: value.MissingTranslations,
		MissingThumbnails:   value.MissingThumbnails,
		LatestUpdatedPosts:  mapAdminDashboardUpdatedPosts(value.LatestUpdatedPosts),
		DominantCategory:    mapAdminDashboardCategory(value.DominantCategory),
	}
}

func mapAdminDashboardUpdatedPosts(items []domain.AdminDashboardUpdatedPost) []*model.AdminDashboardUpdatedPost {
	mapped := make([]*model.AdminDashboardUpdatedPost, 0, len(items))
	for _, item := range items {
		mapped = append(mapped, &model.AdminDashboardUpdatedPost{
			ID:       item.ID,
			Title:    item.Title,
			Date:     item.Date,
			Category: item.Category,
		})
	}

	return mapped
}

func mapAdminDashboardCategory(value *domain.AdminDashboardCategory) *model.AdminDashboardCategory {
	if value == nil {
		return nil
	}

	return &model.AdminDashboardCategory{
		ID:    value.ID,
		Name:  value.Name,
		Count: value.Count,
	}
}

func mapAdminSessions(items []domain.AdminSessionRecord, currentSessionID string) []*model.AdminSession {
	mapped := make([]*model.AdminSession, 0, len(items))
	for _, item := range items {
		mapped = append(mapped, &model.AdminSession{
			ID:             item.ID,
			Device:         resolveAdminDeviceLabel(item.UserAgent),
			IPAddress:      resolveAdminIPAddressLabel(item.RemoteIP),
			CountryCode:    resolveAdminCountryCodeLabel(item.CountryCode),
			LastActivityAt: item.LastSeenAt.UTC().Format(time.RFC3339),
			CreatedAt:      item.CreatedAt.UTC().Format(time.RFC3339),
			ExpiresAt:      item.ExpiresAt.UTC().Format(time.RFC3339),
			Persistent:     item.Persistent,
			Current:        strings.TrimSpace(item.ID) != "" && strings.TrimSpace(item.ID) == strings.TrimSpace(currentSessionID),
		})
	}

	return mapped
}

func resolveAdminDeviceLabel(userAgent string) string {
	normalized := strings.ToLower(strings.TrimSpace(userAgent))
	if normalized == "" {
		return "Unknown device"
	}

	browser := resolveBrowserLabel(normalized)
	os := resolveOSLabel(normalized)
	switch {
	case browser != "" && os != "":
		return browser + " on " + os
	case browser != "":
		return browser
	case os != "":
		return os
	case strings.Contains(normalized, "iphone"),
		strings.Contains(normalized, "android"),
		strings.Contains(normalized, "mobile"):
		return "Mobile browser"
	case strings.Contains(normalized, "ipad"),
		strings.Contains(normalized, "tablet"):
		return "Tablet browser"
	case strings.Contains(normalized, "macintosh"),
		strings.Contains(normalized, "windows"),
		strings.Contains(normalized, "linux"),
		strings.Contains(normalized, "x11"):
		return "Desktop browser"
	default:
		return "Browser"
	}
}

func resolveBrowserLabel(userAgent string) string {
	switch {
	case strings.Contains(userAgent, "edg/"):
		return "Edge"
	case strings.Contains(userAgent, "opr/"), strings.Contains(userAgent, "opera/"):
		return "Opera"
	case strings.Contains(userAgent, "firefox/"):
		return "Firefox"
	case strings.Contains(userAgent, "chrome/"):
		return "Chrome"
	case strings.Contains(userAgent, "safari/"), strings.Contains(userAgent, "version/"):
		return "Safari"
	case strings.Contains(userAgent, "chromium/"):
		return "Chromium"
	default:
		return ""
	}
}

func resolveOSLabel(userAgent string) string {
	switch {
	case strings.Contains(userAgent, "iphone"), strings.Contains(userAgent, "ipad"), strings.Contains(userAgent, "ios"):
		return "iOS"
	case strings.Contains(userAgent, "android"):
		return "Android"
	case strings.Contains(userAgent, "mac os x"), strings.Contains(userAgent, "macintosh"):
		return "macOS"
	case strings.Contains(userAgent, "windows nt"):
		return "Windows"
	case strings.Contains(userAgent, "cros"):
		return "ChromeOS"
	case strings.Contains(userAgent, "linux"), strings.Contains(userAgent, "x11"):
		return "Linux"
	default:
		return ""
	}
}

func resolveAdminIPAddressLabel(ipAddress string) string {
	trimmed := strings.TrimSpace(ipAddress)
	if trimmed == "" {
		return "Unknown"
	}

	return trimmed
}

func resolveAdminCountryCodeLabel(countryCode string) string {
	trimmed := strings.TrimSpace(strings.ToUpper(countryCode))
	if len(trimmed) != 2 {
		return "Unknown"
	}

	return trimmed
}

func resolveCurrentRefreshSessionID(ctx context.Context) string {
	request := getRequest(ctx)
	if request == nil {
		return ""
	}

	config := appconfig.ResolveAdminConfig()
	if strings.TrimSpace(config.JWTSecret) == "" {
		return ""
	}

	refreshCookie, err := request.Cookie(config.RefreshCookieName)
	if err != nil {
		return ""
	}

	claims, err := httpauth.VerifyHS256JWT(strings.TrimSpace(refreshCookie.Value), config.JWTSecret, "refresh", time.Now().UTC())
	if err != nil {
		return ""
	}

	return strings.TrimSpace(claims.ID)
}

func resolveAdminSessionMetadata(ctx context.Context, request *http.Request) appservice.AdminSessionMetadata {
	metadata := appservice.AdminSessionMetadata{}
	if trace, ok := httpapi.RequestTraceFromContext(ctx); ok {
		metadata.RemoteIP = strings.TrimSpace(trace.RemoteIP)
		metadata.UserAgent = strings.TrimSpace(trace.UserAgent)
		metadata.CountryCode = strings.TrimSpace(strings.ToUpper(trace.CountryCode))
	}

	if request != nil && strings.TrimSpace(metadata.UserAgent) == "" {
		metadata.UserAgent = strings.TrimSpace(request.UserAgent())
	}
	if request != nil && strings.TrimSpace(metadata.CountryCode) == "" {
		metadata.CountryCode = resolveCountryCodeFromRequest(request)
	}

	return metadata
}

func resolveCountryCodeFromRequest(request *http.Request) string {
	if request == nil {
		return ""
	}

	for _, header := range []string{"CF-IPCountry", "X-Country-Code", "X-AppEngine-Country"} {
		value := strings.TrimSpace(strings.ToUpper(request.Header.Get(header)))
		if len(value) == 2 {
			return value
		}
	}

	return ""
}

func clearAdminSessionCookies(responseWriter http.ResponseWriter, config appconfig.AdminConfig) {
	httpauth.ClearCookie(responseWriter, config.AccessCookieName, config.SecureCookies, "/")
	httpauth.ClearCookie(responseWriter, config.RefreshCookieName, config.SecureCookies, "/api/admin")
	httpauth.ClearClientCookie(responseWriter, config.CSRFCookieName, config.SecureCookies, "/")
}

func setAdminRefreshCookie(
	responseWriter http.ResponseWriter,
	config appconfig.AdminConfig,
	payload *appservice.AdminAuthResponse,
) {
	if payload == nil {
		return
	}

	if payload.RememberMe {
		httpauth.SetCookie(
			responseWriter,
			config.RefreshCookieName,
			payload.RefreshToken,
			int(payload.RefreshTTL.Seconds()),
			config.SecureCookies,
			"/api/admin",
		)
		return
	}

	httpauth.SetSessionCookie(
		responseWriter,
		config.RefreshCookieName,
		payload.RefreshToken,
		config.SecureCookies,
		"/api/admin",
	)
}
