package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"strings"

	"suaybsimsek.com/blog-api/internal/domain"
	"suaybsimsek.com/blog-api/internal/graphql/model"
	appservice "suaybsimsek.com/blog-api/internal/service"
)

var (
	queryContentFn  = appservice.QueryContent
	queryPostFn     = appservice.QueryPost
	listCommentsFn  = appservice.ListComments
	incrementLikeFn = appservice.IncrementLike
	incrementHitFn  = appservice.IncrementHit
	subscribeFn     = appservice.Subscribe
	resendFn        = appservice.Resend
	confirmFn       = appservice.Confirm
	unsubscribeFn   = appservice.Unsubscribe
	addCommentFn    = appservice.AddComment
)

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, locale model.Locale, input *model.PostsQueryInput) (*model.PostConnection, error) {
	normalizedLocale := strings.TrimSpace(mapLocaleInput(locale))
	if normalizedLocale == "" {
		return nil, fmt.Errorf("locale is required")
	}

	queryInput := appservice.ContentQueryInput{
		Locale: normalizedLocale,
	}
	if input != nil {
		if input.Page != nil {
			queryInput.Page = input.Page
		}
		if input.Size != nil {
			queryInput.Size = input.Size
		}
		if sortOrder := mapSortOrder(input.Sort); sortOrder != "" {
			queryInput.Sort = sortOrder
		}
		queryInput.ScopeIDs = append([]string{}, input.ScopeIds...)
	}

	payload := queryContentFn(ctx, queryInput)
	total := payload.Total
	if total < 0 {
		total = 0
	}

	page := payload.Page
	if page <= 0 {
		page = 1
	}

	size := payload.Size
	if size <= 0 {
		size = len(payload.Posts)
		if size <= 0 {
			size = 1
		}
	}

	return &model.PostConnection{
		Status:     mapContentQueryStatus(payload.Status),
		Locale:     mapLocaleOutput(payload.Locale),
		Nodes:      mapPosts(payload.Posts),
		Engagement: mapEngagement(payload.LikesByPostID, payload.HitsByPostID),
		Total:      total,
		Page:       page,
		Size:       size,
		Sort:       mapResolvedSortOrder(payload.Sort),
	}, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, locale model.Locale, id string) (*model.PostResult, error) {
	normalizedLocale := strings.TrimSpace(mapLocaleInput(locale))
	if normalizedLocale == "" {
		return nil, fmt.Errorf("locale is required")
	}

	normalizedID := strings.TrimSpace(id)
	if normalizedID == "" {
		return nil, fmt.Errorf("id is required")
	}

	payload := queryPostFn(ctx, appservice.PostQueryInput{
		Locale: normalizedLocale,
		PostID: normalizedID,
	})
	var node *model.Post
	mappedNodes := mapPosts(payload.Posts)
	if len(mappedNodes) > 0 {
		node = mappedNodes[0]
	}

	var engagement *model.PostEngagement
	mappedEngagement := mapEngagement(payload.LikesByPostID, payload.HitsByPostID)
	if len(mappedEngagement) > 0 {
		engagement = mappedEngagement[0]
	}

	return &model.PostResult{
		Status:     mapContentQueryStatus(payload.Status),
		Locale:     mapLocaleOutput(payload.Locale),
		Node:       node,
		Engagement: engagement,
	}, nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, locale model.Locale, postID string) (*model.CommentListResult, error) {
	normalizedLocale := strings.TrimSpace(mapLocaleInput(locale))
	if normalizedLocale == "" {
		return nil, fmt.Errorf("locale is required")
	}

	normalizedPostID := strings.TrimSpace(postID)
	if normalizedPostID == "" {
		return nil, fmt.Errorf("postId is required")
	}

	payload := listCommentsFn(ctx, appservice.CommentQueryInput{
		Locale: normalizedLocale,
		PostID: normalizedPostID,
	})

	return &model.CommentListResult{
		Status:  mapCommentQueryStatus(payload.Status),
		Locale:  mapLocaleOutput(payload.Locale),
		PostID:  strings.TrimSpace(payload.PostID),
		Total:   payload.Total,
		Threads: mapCommentThreads(payload.Comments),
	}, nil
}

// IncrementPostLike is the resolver for the incrementPostLike field.
func (r *mutationResolver) IncrementPostLike(ctx context.Context, postID string) (*model.PostMetricResult, error) {
	payload := incrementLikeFn(ctx, postID)
	resolvedPostID := strings.TrimSpace(payload.PostID)
	if resolvedPostID == "" {
		resolvedPostID = strings.TrimSpace(postID)
	}

	result := &model.PostMetricResult{
		Status: mapPostMetricStatus(payload.Status),
		PostID: resolvedPostID,
	}
	if payload.Likes > 0 || result.Status == model.PostMetricStatusSuccess {
		likes := toGraphQLInt(payload.Likes)
		result.Likes = &likes
	}
	if payload.Hits > 0 || result.Status == model.PostMetricStatusSuccess {
		hits := toGraphQLInt(payload.Hits)
		result.Hits = &hits
	}

	return result, nil
}

// IncrementPostHit is the resolver for the incrementPostHit field.
func (r *mutationResolver) IncrementPostHit(ctx context.Context, postID string) (*model.PostMetricResult, error) {
	payload := incrementHitFn(ctx, postID)
	resolvedPostID := strings.TrimSpace(payload.PostID)
	if resolvedPostID == "" {
		resolvedPostID = strings.TrimSpace(postID)
	}

	result := &model.PostMetricResult{
		Status: mapPostMetricStatus(payload.Status),
		PostID: resolvedPostID,
	}
	if payload.Likes > 0 || result.Status == model.PostMetricStatusSuccess {
		likes := toGraphQLInt(payload.Likes)
		result.Likes = &likes
	}
	if payload.Hits > 0 || result.Status == model.PostMetricStatusSuccess {
		hits := toGraphQLInt(payload.Hits)
		result.Hits = &hits
	}

	return result, nil
}

// SubscribeNewsletter is the resolver for the subscribeNewsletter field.
func (r *mutationResolver) SubscribeNewsletter(
	ctx context.Context,
	input model.NewsletterSubscribeInput,
) (*model.NewsletterMutationResult, error) {
	payload := subscribeFn(
		ctx,
		appservice.SubscribeInput{
			Locale:   strings.TrimSpace(mapLocaleInput(input.Locale)),
			Email:    strings.TrimSpace(input.Email),
			Terms:    input.Terms,
			Tags:     append([]string{}, input.Tags...),
			FormName: strings.TrimSpace(toOptionalStringValue(input.FormName)),
		},
		getRequestMetadata(ctx),
	)

	return &model.NewsletterMutationResult{
		Status:    mapNewsletterMutationStatus(payload.Status),
		ForwardTo: toOptionalString(payload.ForwardTo),
	}, nil
}

// ResendNewsletterConfirmation is the resolver for the resendNewsletterConfirmation field.
func (r *mutationResolver) ResendNewsletterConfirmation(
	ctx context.Context,
	input model.NewsletterResendInput,
) (*model.NewsletterMutationResult, error) {
	payload := resendFn(
		ctx,
		appservice.ResendInput{
			Locale: strings.TrimSpace(mapLocaleInput(input.Locale)),
			Email:  strings.TrimSpace(input.Email),
			Terms:  input.Terms,
		},
		getRequestMetadata(ctx),
	)

	return &model.NewsletterMutationResult{
		Status: mapNewsletterMutationStatus(payload.Status),
	}, nil
}

// ConfirmNewsletterSubscription is the resolver for the confirmNewsletterSubscription field.
func (r *mutationResolver) ConfirmNewsletterSubscription(
	ctx context.Context,
	token string,
) (*model.NewsletterMutationResult, error) {
	payload := confirmFn(ctx, strings.TrimSpace(token))
	return &model.NewsletterMutationResult{
		Status: mapNewsletterMutationStatus(payload.Status),
	}, nil
}

// UnsubscribeNewsletter is the resolver for the unsubscribeNewsletter field.
func (r *mutationResolver) UnsubscribeNewsletter(
	ctx context.Context,
	token string,
) (*model.NewsletterMutationResult, error) {
	payload := unsubscribeFn(ctx, strings.TrimSpace(token))
	return &model.NewsletterMutationResult{
		Status: mapNewsletterMutationStatus(payload.Status),
	}, nil
}

// AddComment is the resolver for the addComment field.
func (r *mutationResolver) AddComment(ctx context.Context, input model.AddCommentInput) (*model.CommentMutationResult, error) {
	readerUser := getReaderUser(ctx)

	payload := addCommentFn(
		ctx,
		appservice.AddCommentInput{
			Locale:                       strings.TrimSpace(mapLocaleInput(input.Locale)),
			PostID:                       strings.TrimSpace(input.PostID),
			ParentID:                     strings.TrimSpace(toOptionalStringValue(input.ParentID)),
			AuthorName:                   strings.TrimSpace(input.AuthorName),
			AuthorEmail:                  strings.TrimSpace(input.AuthorEmail),
			AuthenticatedAuthorName:      strings.TrimSpace(toOptionalReaderName(readerUser)),
			AuthenticatedAuthorEmail:     strings.TrimSpace(toOptionalReaderEmail(readerUser)),
			AuthenticatedAuthorAvatarURL: strings.TrimSpace(toOptionalReaderAvatarURL(readerUser)),
			Content:                      input.Content,
		},
		getRequestMetadata(ctx),
	)

	resolvedPostID := strings.TrimSpace(payload.PostID)
	if resolvedPostID == "" {
		resolvedPostID = strings.TrimSpace(input.PostID)
	}

	return &model.CommentMutationResult{
		Status:           mapCommentMutationStatus(payload.Status),
		PostID:           resolvedPostID,
		ModerationStatus: mapCommentModerationStatus(payload.ModerationStatus),
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)

func toOptionalStringValue(value *string) string {
	if value == nil {
		return ""
	}
	return *value
}

func toOptionalReaderName(user *domain.ReaderUser) string {
	if user == nil {
		return ""
	}
	return user.Name
}

func toOptionalReaderEmail(user *domain.ReaderUser) string {
	if user == nil {
		return ""
	}
	return user.Email
}

func toOptionalReaderAvatarURL(user *domain.ReaderUser) string {
	if user == nil {
		return ""
	}
	return user.AvatarURL
}
