version: "3.8"

services:
  blog:
    image: suayb/blog:main
    container_name: blog
    ports:
      - "80:80"
    healthcheck:
      test: curl --fail --silent localhost/health | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  app:
    driver: "bridge"
